### ISSUE TITLE
nvm start issue

### ISSUE THREAD

**Issue by donaghosh** [insidesherpa/JPMC-tech-task-2#102]
![Screenshot (149)](https://user-images.githubusercontent.com/30055109/81557735-1d172180-93aa-11ea-90cd-df0ca2ddac54.png)
![Screenshot (147)](https://user-images.githubusercontent.com/30055109/81557755-21dbd580-93aa-11ea-8fe2-40d8a85c4b6c.png)
![Screenshot (148)](https://user-images.githubusercontent.com/30055109/81557757-230d0280-93aa-11ea-8950-5a034ebe82d6.png)

**Comment by gbit1605** [comment]
You have to perform the npm install in your directory which is as C:\<username>\...

**Comment by roshan007k** [comment]
facing the same issue

**Comment by roshan007k** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/52031155/81563102-76378300-93b3-11ea-8471-a587c5bc81e2.png)

**Comment by roshan007k** [comment]
i have performed the npm install in the username directory

**Comment by donaghosh** [comment]
> You have to perform the npm install in your directory which is as C:<username>...

Thank you.. My issue is resolved
