### ISSUE TITLE
nvm use giving error

### ISSUE THREAD

**Issue by subban358** [insidesherpa/JPMC-tech-task-2#103]
```
nvm install 11.0.0
```

After this command when  I am running

```
nvm use 11.0.0
```

# I am getting the following error

```
exit status 1: 'C:\Users\Subham' is not recognized as an internal or external command,
operable program or batch file.
```

PS: Yes I have tried cmd as admin and also uninstalled and deleted node and npm from machine

**Comment by MARVELMafia** [comment]
Same issue!

**Comment by MARVELMafia** [comment]
Any update?

**Comment by subban358** [comment]
> Any update?
Not yet bro I am stuck here

**Comment by MARVELMafia** [comment]
Bro I found the fix for this. Install it directly into C drive and not into any directory with a space in its name.

**Comment by dheerajodha** [comment]
Hi @subban358 if you have solved the error successfully, please close this issue thanks!

**Comment by lakshya123** [comment]
Did anyone get rid of this error?

**Comment by subban358** [comment]
To fix this issue make sure to install nvm on a folder where there is no space in your path name
