### ISSUE TITLE
ERROR IN NPM INSTALL

### ISSUE THREAD

**Issue by managha** [insidesherpa/JPMC-tech-task-2#104]
i wanted to mention that i didn't install nvm because i had a node and npm in my system already when checked for the version so is it like necessary to do that and can i know why.
Also my visual studio build tool is of  2019`
<img width="948" alt="jp1" src="https://user-images.githubusercontent.com/52420532/81589698-3f736400-93d7-11ea-8c1b-5046fb51cf32.PNG">
<img width="960" alt="jp2" src="https://user-images.githubusercontent.com/52420532/81589726-4bf7bc80-93d7-11ea-9be7-fee6575091b8.PNG">
<img width="960" alt="jp3" src="https://user-images.githubusercontent.com/52420532/81589734-5023da00-93d7-11ea-9ccd-88453209b15e.PNG">

`

**Comment by sumit2498** [comment]
same here

**Comment by gunjan1831** [comment]
![npm install](https://user-images.githubusercontent.com/55911274/81739457-090e1580-94b9-11ea-89a1-5521bef3fbf9.png)

**Comment by gunjan1831** [comment]
I m facing this problem

**Comment by managha** [comment]
Do this...it worked for me.

1.npm install --force
2.npm audit fix
3.npm start

giv npm config set msvs_version 2019 if u hav installed 2019 version

**Comment by gunjan1831** [comment]
Oh okay I'll try.  Thanks a lot

**Comment by MARVELMafia** [comment]
@managha I tried what you suggested but still get error
![image](https://user-images.githubusercontent.com/28630442/81844316-08937e80-958e-11ea-9b51-9c246834f63d.png)

**Comment by managha** [comment]
> @managha I tried what you suggested but still get error
> ![image](https://user-images.githubusercontent.com/28630442/81844316-08937e80-958e-11ea-9b51-9c246834f63d.png)

yes, try doing that 4 steps mentioned..even i got tht error once.

**Comment by MARVELMafia** [comment]
> > @managha I tried what you suggested but still get error
> > ![image](https://user-images.githubusercontent.com/28630442/81844316-08937e80-958e-11ea-9b51-9c246834f63d.png)
> 
> yes, try doing that 4 steps mentioned..even i got tht error once.

Which 4 steps?

**Comment by managha** [comment]
The four steps mentioned in the error message about fixing the dependency
tree

**Comment by MARVELMafia** [comment]
Any idea about what to do in step 3? Should I delete the eslint code in the package.json file?

**Comment by managha** [comment]
Yes or else if u have Devdependencies then remove tht. Either one

**Comment by MARVELMafia** [comment]
I deleted the dependencies and now I am getting this 
Any help will be appreciated, I'm stuck on this for like almost a week now :(
![image](https://user-images.githubusercontent.com/28630442/82081094-e4b67100-9724-11ea-83fb-60b71a5755d7.png)

**Comment by managha** [comment]
Can u pls try the 3  steps again now... Tht i mentioned first above..

 1.npm install --force
2.npm audit fix
 3.npm start

Im sorry even i hav no much idea but this wat all i tried 😅😅

**Comment by MARVELMafia** [comment]
Thanks for the help! Although, I just swtiched to linux and used wsl and it seems to work. 
Just have a query about this :  
![image](https://user-images.githubusercontent.com/28630442/82118337-e3815480-97b5-11ea-85c2-e2b62352f67b.png)
![image](https://user-images.githubusercontent.com/28630442/82118362-1b889780-97b6-11ea-9720-d579177a9327.png)

In which function do we make these changes in the Graph.tsx?

**Comment by Yash-Bhange** [comment]
![q](https://user-images.githubusercontent.com/60029585/82119595-7b267900-979d-11ea-914f-e8b2b26317b5.png)

**Comment by Yash-Bhange** [comment]
also  after runnig server3.py and client3.py  , it shown output on cmd  but on localhost 3000 it show error . i have tried  port 8080, 8085, but nothing works

**Comment by managha** [comment]
Along with
 elem.load(this.table)
U can see the comments there

**Comment by managha** [comment]
So is ur
python datafeed/server3.py and
npm start
Giving u any trouble?

**Comment by Yash-Bhange** [comment]
i just resolved my issue  thanks for help

**Comment by khanh4** [comment]
I am confused about the python data feed/server3.py. Every time I do that nothing happens. Where am I suppose to use that. I am stuck on this for few days now.

**Comment by khanh4** [comment]
Can someone help I did the 3 steps you said to do. But I can’t stream the data. I changed the port from 8080 to 8085. And it’s still not working.

**Comment by managha** [comment]
This command  should b given inside the git file you initially cloned.if
its working well you will get a msg showing the activated port number.

**Comment by khanh4** [comment]
Hi @managha i am getting this error can you help please. 
![image](https://user-images.githubusercontent.com/65410306/82334242-b4393600-99b5-11ea-85b2-a83e28938848.jpg)

**Comment by managha** [comment]
Ok you r not suppose to give that command inside the python... But u hav to
give that inside the jpmc-tech-task-2-py3 directory.
For this u can either open ur cmd window inside that file or navigate to it
using cd commands.
Hope this helps

**Comment by dheerajodha** [comment]
HI @managha if you have successfully solved your issue, can you please close this issue? Thank you!

**Comment by parth2510** [comment]
> Do this...it worked for me.
> 
> 1.npm install --force
> 2.npm audit fix
> 3.npm start
> 
> giv npm config set msvs_version 2019 if u hav installed 2019 version


this works like a charm, thanks;
seems this issue is experienced by many, moderator should tell them this
