### ISSUE TITLE
nvm use 11.0.0 giving error

### ISSUE THREAD

**Issue by MARVELMafia** [insidesherpa/JPMC-tech-task-2#111]
```
exit status 1: 'C:\Users\Amrit' is not recognized as an internal or external command,
operable program or batch file.
```

**I have updated the nvm path in my system environment variables but still facing the error.** 
**I have also tried running with Administrator - CMD.**

![image](https://user-images.githubusercontent.com/28630442/81679954-c4bb4f00-9491-11ea-90f0-8fd5afdebe10.png)

Error Screen Shot: 

![image](https://user-images.githubusercontent.com/28630442/81680153-f3392a00-9491-11ea-914e-36ae66aefb7f.png)

**Comment by managha** [comment]
can u lik try going to the directory where u hav nvm nd running the command.I have no much idea on it bcz i didnt download nvm so its just a guess

**Comment by MARVELMafia** [comment]
Thanks for the advice. I found the fix for it. But am facing more errors lol will create a new issue post
