### ISSUE TITLE
HTTP server 8080 error//datafeed

### ISSUE THREAD

**Issue by Kshitij031998** [insidesherpa/JPMC-tech-task-2#113]
It is showing missing parenthesis error. Server not running
![Screenshot (135)](https://user-images.githubusercontent.com/44141019/81680762-3d5de380-9471-11ea-8c1d-2d0319f970a9.png)

**Comment by MARVELMafia** [comment]
I think you're using python 3.+. So may you need to run the server3.py from JPMC-tech-task-2-PY3.
