### ISSUE TITLE
not able to create patch file

### ISSUE THREAD

**Issue by managha** [insidesherpa/JPMC-tech-task-2#116]
git commit -m 'Create Patch File'
error: pathspec 'Patch' did not match any file(s) known to git
error: pathspec 'File'' did not match any file(s) known to git

im in the /JPMC-tech-task-2-PY3 directory itself

and using the command

git format-patch -1 HEAD
gives me
0001-Update-README-setupv8.patch

but im not sure if it is the updated one.pls help out

**Comment by MARVELMafia** [comment]
Hi, sorry I wanted to ask you if you could help me out with my query. I can't seem to get nvm to function properly. https://github.com/insidesherpa/JPMC-tech-task-2/issues/111

Any ideas?
