### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by harnoor497** [insidesherpa/JPMC-tech-task-2#121]
not getting the data 
![Screenshot 2020-05-14 at 12 21 00 AM](https://user-images.githubusercontent.com/63140074/81904098-6b156a80-95e0-11ea-9309-b57d9dca9771.png)

When clicking on Start data streaming i got the foll error .
![Screenshot 2020-05-14 at 11 38 36 AM](https://user-images.githubusercontent.com/63140074/81904072-5d5fe500-95e0-11ea-9c4a-1734e8c6f410.png)

tried by changing the port to 8085 bt no solution.
can anyone please help me out.

**Comment by subban358** [comment]
I am facing the same

**Comment by harnoor497** [comment]
if you are able to resolve the issue . please tell me too .

**Comment by thebit1701** [comment]
I am facing the same issue.
