### ISSUE TITLE
Server.py not loading

### ISSUE THREAD

**Issue by BhargavReddyg** [insidesherpa/JPMC-tech-task-2#122]
![image](https://user-images.githubusercontent.com/65347488/81936261-9794ab00-960f-11ea-99c0-3d8606c84522.png)

I tried using "python datafeed/server.py" I am getting no such file or directory found error.  I even tried using "python3 datafeed/server3.py" nothing is being shown after it. **I am getting HTTP server started on port 8080.** .Please help me in resolving this issue

![image](https://user-images.githubusercontent.com/65347488/81937026-a9c31900-9610-11ea-8cad-20973d58c440.png)

I even tried **python datafeed/server3.py** I am getting error as shown in screenshot please help me out

**Comment by BhargavReddyg** [comment]
![image](https://user-images.githubusercontent.com/65347488/81937026-a9c31900-9610-11ea-8cad-20973d58c440.png)


I even tried python datafeed/server3.py I am getting error as shown in screenshot please help me out

**Comment by dheerajodha** [comment]
Hi @BhargavReddyg , try this :
-Temporarily turn off your firewall
-Using any text editor, open the datafeed/server.py in the repository using your code editor and look for the line where it says port = 8080. change that to port = 8085
-Similarly, open the src/DataStreamer.ts and change the line where it has 8080 to 8085

**Comment by BhargavReddyg** [comment]
Thanks for the help got if after changing the port no and turning off firewall

**Comment by dheerajodha** [comment]
Really happy to know!
The instructions I shared with you above are actually copied from the Dev environment setup pdf file of InsideSherpa which you used, to follow procedures. 
More specifically, these instructions are mentioned under the Troubleshooting section.
So, please give those steps a try first before opening an issue, thanks!

**Comment by CyberSaiyam** [comment]
Mine is still not working.
