### ISSUE TITLE
Error while using npm start in task 2

### ISSUE THREAD

**Issue by atulya06** [insidesherpa/JPMC-tech-task-2#123]
![Screenshot (63)](https://user-images.githubusercontent.com/51713368/81966601-5e703100-9637-11ea-98de-ab61dc6ca500.png)

**Comment by jeeva2812** [comment]
The module has been shifted to @finos/perspective ig.

This worked for me,

run
`npm i @finos/perspective`
and change line 2 to:
`import { Table } from '@finos/perspective';`

**Comment by atulya06** [comment]
@jeeva2812 thanks a lot! worked for me as well.
