### ISSUE TITLE
Graph is not shown.

### ISSUE THREAD

**Issue by sachinsrt7** [insidesherpa/JPMC-tech-task-2#126]
![error3](https://user-images.githubusercontent.com/63451675/82043672-a17ae480-96c9-11ea-835b-8f1dbb15d5fa.png)

**Comment by jeeva2812** [comment]
Can you please inspect the webpage and check if there is any error reported in the console.

**Comment by dheerajodha** [comment]
I had the same problem, I restarted my PC and then started the server again, executed npm start again, and surprisingly it worked.

**Comment by sachinsrt7** [comment]
Thanks for replying and I have successfully completed the task.

**Comment by dheerajodha** [comment]
Very good to know! Happy coding!
