### ISSUE TITLE
Failed to Compile-Type Error TS2345

### ISSUE THREAD

**Issue by Mexxy-lab** [insidesherpa/JPMC-tech-task-2#13]
Team, 

I edited the graph.tsx file as shown however i keep getting this type error which is making the system not to compile well. What can i do differently please.

![image](https://user-images.githubusercontent.com/49109013/69473980-96817000-0d88-11ea-91a7-a12bf63a1f93.png)

![image](https://user-images.githubusercontent.com/49109013/69473988-b31da800-0d88-11ea-81ba-ad2d7120b4c4.png)

**Comment by jbf-insidesherpa** [comment]
@Mexxy-lab there a couple things you got wrong in your code.

For starters, for better syntax highlighting, may I suggest you install the typescript plugin for sublime text:
https://packagecontrol.io/packages/TypeScript

As for the stuff you got incorrectly
1. it should be `elem.setAttribute('column-pivots', '["stock"]');
2. in the aggregates property, the value should have been enclosed in back ticks i.e. `
so it would look somethine like: `elem.setAttribute('aggregates', '{"stock":"distinct count","top_ask_price":"avg","top_bid_price":"avg","timestamp":"distinct count"}');`

**Comment by Mexxy-lab** [comment]
Thanks fixed.
