### ISSUE TITLE
Issue while running NPM INSTALL

### ISSUE THREAD

**Issue by Shweta94Me** [insidesherpa/JPMC-tech-task-2#132]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\{{yourMachineName}}\\AppData\\Roaming\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ..\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{{yourMachineName}}\AppData\Roaming\npm-cache\_logs\2020-05-16T00_52_00_643Z-debug.log

**Comment by prachisawarkar** [comment]
I am also getting the same issue. I am stuck with it from about 3-4 days. Please help.

**Comment by dsrao711** [comment]
same issue

**Comment by dheerajodha** [comment]
Hi Sweta, are you running "npm install" command **inside** your cloned project folder (ie. inside JPMC-tech-task-2)?
Also, tell me if your "JPMC-tech-task-2" folder has a folder named "node_modules" inside it.

**Comment by ztasnim** [comment]
> Hi Sweta, are you running "npm install" command **inside** your cloned project folder (ie. inside JPMC-tech-task-2)?
> Also, tell me if your "JPMC-tech-task-2" folder has a folder named "node_modules" inside it.

Hi, even I’m having the same issue. I do have a “node_modules” folder inside “JPMC-tech-task-2” folder.

**Comment by dheerajodha** [comment]
Hello @ztasnim so I'm assuming that you get this error once you run "npm install" **from the folder where you have cloned your JPMC project**.

Can you try this out? 
Run this command from an **administrative** **shell** to install the "software" dependencias (Visual Studio, Python) on windows:

    npm install --global --production windows-build-tools

    npm install -g node-gyp

    npm install

Note : Execute these commands from inside the project folder where you cloned your JPMC project.

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by ztasnim** [comment]
> Hello @ztasnim so I'm assuming that you get this error once you run "npm install" **from the folder where you have cloned your JPMC project**.
> 
> Can you try this out?
> Run this command from an **administrative** **shell** to install the "software" dependencias (Visual Studio, Python) on windows:
> 
> ```
> npm install --global --production windows-build-tools
> 
> npm install -g node-gyp
> 
> npm install
> ```
> 
> Note : Execute these commands from inside the project folder where you cloned your JPMC project.
> 
> If you get some more errors, then post your error screenshots here.
> If you've already solved your issue, please close this 

Thank you for the help! One more query, is there any problem if I do task 1 in python version 3 and task 2 in python version 2?

**Comment by dheerajodha** [comment]
@ztasnim  I'm not sure about that, can you email the InsideSherpa team via an email or Live chat (It's in their site) and post your query there? 
Plus, did your previous error got resolved?

**Comment by ztasnim** [comment]
Yes thanks! I’m facing another issue with the graph 
![CCA78AD5-CC96-47BA-BD9C-E195157B2294](https://user-images.githubusercontent.com/59805572/82468295-75ee6480-9ae4-11ea-817e-a5d21d69cc4e.jpeg)


> @ztasnim I'm not sure about that, can you email the InsideSherpa team via an email or Live chat (It's in their site) and post your query there?
> Plus, did your previous error got resolved?

**Comment by dheerajodha** [comment]
Hi @ztasnim I'm not sure but the reason behind this might be the fact that your data is not being able to get fetched from server, or there are some mistakes in your code when you work with the fetched data, this can be reason why your data is not able to get rendered here on screen.

Please go through your code properly (wherever you made changes) "line by line" and find if there's some minute mistake, or maybe open your developer console and see if there's any error caught up there.

**Comment by ztasnim** [comment]
> Hi @ztasnim I'm not sure but the reason behind this might be the fact that your data is not being able to get fetched from server, or there are some mistakes in your code when you work with the fetched data, this can be reason why your data is not able to get rendered here on screen.
> Please go through your code properly (wherever you made changes) "line by line" and find if there's some minute mistake, or maybe open your developer console and see if there's any error caught up there.

Hi, thanks it is working now. do you know why I am unable to patch file? 
![image](https://user-images.githubusercontent.com/59805572/82478747-2d8a7300-9af3-11ea-92ab-ce255e3cd83c.png)

**Comment by ztasnim** [comment]
and using the command
git format-patch -1 HEAD
gives me
0001-Update-README-setupv8.patch

**Comment by dheerajodha** [comment]
Yes @ztasnim , while writing commit message in Windows, enclose your message inside double-quotes. Basically replace 'Create Patch File' with "Create Patch File".

**Comment by Harikeshnimma** [comment]
Microsoft Windows [Version 10.0.18362.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd \Users\dell\JPMC-tech-task-2

C:\Users\dell\JPMC-tech-task-2>npm install --global --production windows-build-tools
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> windows-build-tools@5.2.2 postinstall C:\Program Files\nodejs\node_modules\windows-build-tools
> node ./dist/index.js



Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\dell\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.18 is already installed, not installing again.

Now configuring the Visual Studio Build Tools..

All done!

+ windows-build-tools@5.2.2
updated 1 package in 20.651s

C:\Users\dell\JPMC-tech-task-2>npm install -g node-gyp
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
C:\Program Files\nodejs\node-gyp -> C:\Program Files\nodejs\node_modules\node-gyp\bin\node-gyp.js
+ node-gyp@5.1.1
updated 1 package in 7.36s

C:\Users\dell\JPMC-tech-task-2>npm install

> bufferutil@3.0.5 install C:\Users\dell\JPMC-tech-task-2\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\dell\JPMC-tech-task-2\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dell\\AppData\\Roaming\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dell\JPMC-tech-task-2\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2020-05-25T10_55_16_958Z-debug.log

C:\Users\dell\JPMC-tech-task-2>
I have tried the same steps but ended up getting the same error

**Comment by dheerajodha** [comment]
Hi @Harikeshnimma  try this : https://github.com/nodejs/node-gyp/issues/792#issuecomment-153095874

**Comment by varunpatil345** [comment]
@dheerajodha Hello Dheeraj, I am getting the same error, I even tried tried what you mentioned, no luck.

> Hi @Harikeshnimma try this : [nodejs/node-gyp#792 (comment)](https://github.com/nodejs/node-gyp/issues/792#issuecomment-153095874)

**Comment by dheerajodha** [comment]
@varunpatil345 Hi Varun, can you please post your full error snippets?
And your OS, python version as well.
