### ISSUE TITLE
Please help me facing this when npm install and npm start

### ISSUE THREAD

**Issue by JAIS0N** [insidesherpa/JPMC-tech-task-2#134]
![image](https://user-images.githubusercontent.com/46769916/82119782-e290f880-979e-11ea-8bd1-057cca7de25d.png)

PS: nvm and npm is installed it shows when you type nvm -v and npm -v
Edit: Changing directory to JPMC also doesnt work

**Comment by Udit3008** [comment]
I am also getting the same error, even after changing directories and trying some tricks from other github repos.
everything went fine till "npm install" but when I am trying to execute "npm start", it shows this error:
![image](https://user-images.githubusercontent.com/43252805/82124429-9fde1900-97bc-11ea-86b4-85c0f8c81a63.png)

**Comment by thebit1701** [comment]
@Udit3008  Please change your directory to exact location where you want to run "npm start" i.e
- JPMC-tech-task-3-py  then execute "npm start"

**Comment by JAIS0N** [comment]
> @Udit3008 Please change your directory to exact location where you want to run "npm start" i.e
> 
> * JPMC-tech-task-3-py  then execute "npm start"

Done Brother still doesnt work

**Comment by Udit3008** [comment]
@thebit1701 , did this but then it shows node_modules is missing so I tried to copied that also.
after copying when I executed, this error came up
![image](https://user-images.githubusercontent.com/43252805/82138544-effdbf80-983e-11ea-9277-d7aa9bd03c14.png)
what to do now?

**Comment by JAIS0N** [comment]
> @Udit3008 Please change your directory to exact location where you want to run "npm start" i.e
> 
> * JPMC-tech-task-3-py  then execute "npm start"

![image](https://user-images.githubusercontent.com/46769916/82142528-9f945b00-985a-11ea-9ce5-b7376da85137.png)
Please help me

**Comment by madhura14** [comment]
Download node_modules from the link given in the setup document.
replace this old node_modules from the project folder with the new one.

Then npm start from the project folder.

**Comment by JAIS0N** [comment]
> Download node_modules from the link given in the setup document.
> replace this old node_modules from the project folder with the new one.
> 
> Then npm start from the project folder.

Thank you so much Madhura !! This helped me I was just about to quit
![image](https://user-images.githubusercontent.com/46769916/82206516-03378a80-9926-11ea-9719-126bfc3586da.png)

**Comment by Udit3008** [comment]
but there is no folder with name node_modules in "JPMC-tech-task-3-py"
please help with the path where I have to replace old node_modules with new one?

**Comment by madhura14** [comment]
If you haven't installed npm with 'npm install' command.
Then you need to just copy and paste the node_modules folder. (Download it from the link given in the setup doc).

Then npm start from the project folder.

**Comment by Udit3008** [comment]
After just pasting the "node_modules" in project folder and running npm start in same, its showing:
![image](https://user-images.githubusercontent.com/43252805/82224954-253f0600-9942-11ea-8e48-db205c6f6778.png)

**Comment by Udit3008** [comment]
please help @madhura14 !

**Comment by madhura14** [comment]
Just add:
;C:\Program Files\nodejs\

accepted | Just add:;C:\Program Files\nodejs\To the end of your Path variable on the "User variable" section of the Environment Variables on the System Properties.
After that, reopen your command prompt and type
npm

**Comment by Udit3008** [comment]
still not working @madhura14

**Comment by Udit3008** [comment]
please help me out, I am stuck at this step from past 3 days and its frustrating me now. I am trying again and again with new ways. Please help me out, I don't want to quit!!!!!!

**Comment by JAIS0N** [comment]
> still not working @madhura14

Listen reinstall everything git , nvm and VS C++ again and do fresh start. If npm install still doesnt work download from google drive link and replace it with node_modules in C/users/yourname/jpmctask . Press shift then right click open powershell window and run npm start

**Comment by Udit3008** [comment]
I did that too bro, I just removed everything and did the second task from starting but again it stuck at the same point.
Let me try this to paste at this path, may be it works. Thanks bro. let me try it.

**Comment by Udit3008** [comment]
still not working bro @JAIS0N , @madhura14

**Comment by Udit3008** [comment]
what's this error for?
![image](https://user-images.githubusercontent.com/43252805/82237488-51af4e00-9953-11ea-8748-43352b03c1be.png)

**Comment by JAIS0N** [comment]
Idk man , is it because your project folder is in U drive instead of C\Users where it should be

> what's this error for?
> ![image](https://user-images.githubusercontent.com/43252805/82237488-51af4e00-9953-11ea-8748-43352b03c1be.png)
