### ISSUE TITLE
Can someone please help me with this issue and tell me what should i do to solve it

### ISSUE THREAD

**Issue by prachirathod99** [insidesherpa/JPMC-tech-task-2#137]
![img](https://user-images.githubusercontent.com/65258327/82131836-7c5ca380-97a7-11ea-9a7f-e374f4053003.png)

**Comment by dheerajodha** [comment]
Hi Prachi, it looks like maybe you made some small mistake while typing, for your reference I'm posting the full code of the setInterval() : 
const interval = setInterval(() => {
      **DataStreamer.getData((serverResponds: ServerRespond[]) => {
        this.setState({
          data: serverResponds,
          showGraph: true,**
        });
      });
      x++;
      if (x > 1000) {
        clearInterval(interval);
      }
    }, 100);

**Comment by prachirathod99** [comment]
Thank you so much. This was very helpful.

**Comment by dheerajodha** [comment]
My pleasure, just please double-check your code before opening an issue. Happy Coding!
