### ISSUE TITLE
Cannot find module '@jpmorganchase/perspective'.  TS2307

### ISSUE THREAD

**Issue by bhanuteja2001** [insidesherpa/JPMC-tech-task-2#138]
![Screenshot (119)](https://user-images.githubusercontent.com/44323155/82136825-49f68900-982f-11ea-9519-d7cbc5455429.png)
![Screenshot (120)](https://user-images.githubusercontent.com/44323155/82136827-4b27b600-982f-11ea-9da2-30a8ebbeb888.png)

**Comment by Abhishek183** [comment]
i found the same error

**Comment by vaishnaviaddaguduru** [comment]
i got the same error

**Comment by sejalprasad** [comment]
https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view

Download this zip file and replace it with the node modules folder in JPMC-tech-task-2.
Run 'npm install' and 'npm start' commands again

**Comment by Aronray1** [comment]
Perspective is a visualizer used to plot real time datasets,  It seems that you don't have this. First install that component, as the file is asking perspective for generating the graph.

**Comment by Aronray1** [comment]
You can download perspective from JP morgan github perspective repo.
