### ISSUE TITLE
Unable to save changes in App.tsx

### ISSUE THREAD

**Issue by rvenga** [insidesherpa/JPMC-tech-task-2#143]
When I try to save my edited code I get the following error, please help.
![Screenshot (7)](https://user-images.githubusercontent.com/63960557/82213942-e04cac80-990c-11ea-8bfe-9bf1768be76c.png)

**Comment by dheerajodha** [comment]
Hi, I'm not sure but this seems like a permission issue you're having maybe because of the folder you're working in.

Can you move you folder to a different location like "My Documents" or "Documents" and then work on this file & try saving it?

**Comment by rvenga** [comment]
hey thanks, it worked for me
