### ISSUE TITLE
Can't see the graphs on any browser

### ISSUE THREAD

**Issue by akshatbahety** [insidesherpa/JPMC-tech-task-2#15]
Very Simply I tried both Chrome and Firefox it doesn't seem to be running , query is getting recieved and everything else is great but can't see graph.

**Comment by jbf-insidesherpa** [comment]
@akshatbahety have you made any changes to the code already or this is still in the setup phase?

**Comment by jbf-insidesherpa** [comment]
@akshatbahety I'm closing this issue now since it's been a while. Feel free to re-open if necessary

**Comment by akshatbahety** [comment]
Hi was busy with college exams it's still in setup phase.

**Comment by jbf-insidesherpa** [comment]
Cool @akshatbahety. Let me know if you encounter other problems. Feel free to reopen this ticket if it's related.

**Comment by Sankalparora** [comment]
@jbf-insidesherpa 
COMPILATION ERROR IN BUILD TIME I AM NOT ABLE TO UNDERSTAND
![er](https://user-images.githubusercontent.com/42678821/81549818-f3a3c900-939c-11ea-8802-38d2fe63fd60.PNG)

**Comment by kajal91097** [comment]
Use a semi colon instead of colon... its setAttribute   and not setattribute
