### ISSUE TITLE
npm installation issue

### ISSUE THREAD

**Issue by dsrao711** [insidesherpa/JPMC-tech-task-2#152]
I  have installed visual studio build tools and latest version of python
![IMG_20200519_205523](https://user-images.githubusercontent.com/59830064/82347451-40c71100-9a15-11ea-9e59-d4899f9d58fc.jpg)

I am facing this issue , please help

**Comment by dheerajodha** [comment]
Hi @dsrao711 you need to execute this command "npm install" **inside** your folder where you cloned the project, and after that use "npm start".
If you still get error(s), please post the screenshots here.
If this solves your issue, or its been already solved then please close this issue, thanks!

**Comment by parth2510** [comment]
https://github.com/insidesherpa/JPMC-tech-task-2/issues/104#issuecomment-627747878

if you're still stuck
