### ISSUE TITLE
not able to create patch file

### ISSUE THREAD

**Issue by dsrao711** [insidesherpa/JPMC-tech-task-2#155]
![IMG_20200520_005526](https://user-images.githubusercontent.com/59830064/82369562-d8882780-9a34-11ea-8453-d639605d0e9f.jpg)
please help

**Comment by dheerajodha** [comment]
@dsrao711 Use double quotes while writing the commit message, like this : 
git commit -m **"**Create Patch File**"**

If this solves your problem then please **close** the issue.
You've opened some issues before as well, if those haven't been resolved yet then post the error messages there, or if they've solved then close those issues, thank you.

**Comment by dsrao711** [comment]
thank you
