### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by Surajv311** [insidesherpa/JPMC-tech-task-2#157]
I am getting the following errors while running npm install : 
Please help.
![error](https://user-images.githubusercontent.com/59371846/82406434-3abc4900-9a84-11ea-8026-9060c5817c4c.jpg)
![error_](https://user-images.githubusercontent.com/59371846/82406442-40b22a00-9a84-11ea-9536-8b66b9fddc83.jpg)
![error__](https://user-images.githubusercontent.com/59371846/82406445-4445b100-9a84-11ea-989b-542d466b6b94.jpg)

**Comment by dheerajodha** [comment]
Hi @Surajv311 
Run this command from an **administrative** **shell** to install the "software" dependencias (Visual Studio, Python) on windows:

1) npm install --global --production windows-build-tools

2) npm install -g node-gyp

3) npm install

Note : Execute these commands from inside the project folder where you cloned your JPMC project.

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by Surajv311** [comment]
@dheerajodha 
After running npm install I am again getting errors . I used administrative PowerShell and ran the commands.

![err](https://user-images.githubusercontent.com/59371846/82418472-a90c0600-9a9a-11ea-9aa3-1bb75b12c01a.jpg)
![errr](https://user-images.githubusercontent.com/59371846/82418583-c8a32e80-9a9a-11ea-8d8d-873e78e436fe.jpg)
![eerr](https://user-images.githubusercontent.com/59371846/82418450-a3aebb80-9a9a-11ea-9e92-a418cecbc2cd.jpg)

**Comment by dheerajodha** [comment]
@Surajv311 Can you try this and tell me what you get? https://github.com/insidesherpa/JPMC-tech-task-2/issues/40#issuecomment-619541449

**Comment by Surajv311** [comment]
@dheerajodha 
Thanks I can now my npm install command works, But npm start is not working. It's displaying the following error : 
![err](https://user-images.githubusercontent.com/59371846/82425851-bc23d380-9aa4-11ea-9eb1-c1624a23c45d.jpg)

**Comment by dheerajodha** [comment]
Run this : npm install react-scripts --save

**Comment by Surajv311** [comment]
@dheerajodha 
No. It's still not working.
![err](https://user-images.githubusercontent.com/59371846/82434023-ecbd3a80-9aaf-11ea-9c27-4c8254fcd523.jpg)

**Comment by dheerajodha** [comment]
Oh okay, must be an error due to incomplete installation of dependencies.
I referred this answer : https://stackoverflow.com/a/49505612
1) "npm cache clean --force"
2) Delete node_modules folder
3) Delete package-lock.json file too
4) "npm install"
5) "npm start"

And let me know what you get.

**Comment by Surajv311** [comment]
@dheerajodha  Done it's working . Thanks.
![done](https://user-images.githubusercontent.com/59371846/82436093-e7152400-9ab2-11ea-8a6a-9f7ba08470fa.jpg)
![d](https://user-images.githubusercontent.com/59371846/82436099-ea101480-9ab2-11ea-9d67-4b9eb0d0b6bb.jpg)
