### ISSUE TITLE
.ts file showing compile error : TS2365

### ISSUE THREAD

**Issue by Surajv311** [insidesherpa/JPMC-tech-task-2#161]
After running the perspective. My datamanipulator.ts file is throwing compile errors.
How to resolve this error ? 

![11](https://user-images.githubusercontent.com/59371846/82475296-e5b31e00-9ae9-11ea-8d43-aba7491f46d4.jpg)
![err](https://user-images.githubusercontent.com/59371846/82475303-e9df3b80-9ae9-11ea-91fd-69c61910cafa.jpg)

**Comment by dheerajodha** [comment]
@Surajv311 that's weird, I have not experienced this error nor did anyone else. Maybe there is problem while fetching data from the server. 

I would suggest you to double check your code, you might have did a minute mistake while coding.

**Comment by Surajv311** [comment]
@dheerajodha  Yes you are right. A small mistake, I have rectified it. Thanks bro.

**Comment by dheerajodha** [comment]
@Surajv311 Please cross-check your code for any typing mistake, before opening up an issue, thanks!
