### ISSUE TITLE
error in graph.tsx file

### ISSUE THREAD

**Issue by Gargi1010** [insidesherpa/JPMC-tech-task-2#163]
Property 'perspective' does not exist on type 'Window & typeof globalThis'.ts(2339)

Getting this error even though every import was succesful

![error](https://user-images.githubusercontent.com/61877906/82530353-b7215b80-9b5a-11ea-9a70-db3fc8b1a096.png)

**Comment by dheerajodha** [comment]
@Gargi1010 Before opening an issue recheck your code couple of times to find a typing mistake.
You'll find your mistake if you check properly.
