### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by thomazdavis** [insidesherpa/JPMC-tech-task-2#167]
tried installing using :

npm install --global --production windows-build-tools
npm install -g node-gyp
npm install

but still getting errors
![Screenshot (46)](https://user-images.githubusercontent.com/64890136/82699239-e5518900-9c89-11ea-8609-49ba14f47124.png)

**Comment by dheerajodha** [comment]
HI @thomazdavis this might be an error due to incomplete installation of dependencies.
I referred this answer : https://stackoverflow.com/a/49505612

   - Execute "npm cache clean --force"
   - Delete node_modules folder
   - Delete package-lock.json file too
   - Execute "npm install"
   - Execute "npm start"

And let me know what you get.

**Comment by thomazdavis** [comment]
similar errors



> HI @thomazdavis this might be an error due to incomplete installation of dependencies.
> I referred this answer : https://stackoverflow.com/a/49505612
> 
> * Execute "npm cache clean --force"
> * Delete node_modules folder
> * Delete package-lock.json file too
> * Execute "npm install"
> * Execute "npm start"
> 
> And let me know what you get.

**Comment by thomazdavis** [comment]
Similar issue  again

![Screenshot (50)](https://user-images.githubusercontent.com/64890136/82723948-23819380-9cf0-11ea-8237-0219ad1b6a19.png)
![Screenshot (51)](https://user-images.githubusercontent.com/64890136/82723954-27151a80-9cf0-11ea-817d-5fb8179d51e0.png)

**Comment by dheerajodha** [comment]
Can you try this ? https://github.com/insidesherpa/JPMC-tech-task-2/issues/40#issuecomment-619541449

**Comment by thomazdavis** [comment]
still getting errors!

![Screenshot (57)](https://user-images.githubusercontent.com/64890136/82783339-ddf1d180-9e7b-11ea-8924-d0e2594b18b4.png)
![Screenshot (59)](https://user-images.githubusercontent.com/64890136/82783342-dfbb9500-9e7b-11ea-9176-8900cb6386e7.png)

**Comment by dheerajodha** [comment]
@thomazdavis  I'm not sure what causes that error, but does your JPMC-tech-task folder contain a folder named "node_modules"?

**Comment by thomazdavis** [comment]
yes

**Comment by thomazdavis** [comment]
Issued solved

npm install -- force
npm audit
npm start
