### ISSUE TITLE
NPM install getting error  Can't find Python executable "python3.8"

### ISSUE THREAD

**Issue by sagarvbdm** [insidesherpa/JPMC-tech-task-2#171]
![Screenshot (42)](https://user-images.githubusercontent.com/51256950/82734452-afb7a900-9d38-11ea-9b32-1490766f0ac4.png)
![Screenshot (44)](https://user-images.githubusercontent.com/51256950/82734455-b2b29980-9d38-11ea-93df-1f4821e26dbc.png)

i am getting an error all the things are right ,and i followed the all guidelines is setup pdf.
and also tried 
npm install --global --production windows-build-tools
npm install -g node-gyp
npm install
npm start

but nothing works please help me as soon as possible..

**Comment by dheerajodha** [comment]
Hi @sagarvbdm this might help : https://github.com/insidesherpa/JPMC-tech-task-2/issues/40#issuecomment-619541449

**Comment by sagarvbdm** [comment]
tried but not working
