### ISSUE TITLE
NPM Install Error

### ISSUE THREAD

**Issue by Rohit2212** [insidesherpa/JPMC-tech-task-2#172]
This error is the case 3 error as specified in the pdf.
![error](https://user-images.githubusercontent.com/41390965/82738624-99204a80-9d56-11ea-995c-cb3f56f44eca.PNG)
However I have saved my file in users directory only.
The full path is : C:\Users\Sony_Owner\Desktop\VirtualInternship\Task 2\JPMC-tech-task-2
Please help me solve this issue.

**Comment by dheerajodha** [comment]
I don't if it would help but please don't use [space] in path, you has Task[space]2 can you change that to Task2 and try again? Let me know what you get.

**Comment by Rohit2212** [comment]
I removed the space as you suggested and I also downloaded VS studio build tools version 2017 instead of 2019 and somehow my bug was fixed. Thank you so much
