### ISSUE TITLE
Error appearing in CMD after running npm install 

### ISSUE THREAD

**Issue by srisubhashp** [insidesherpa/JPMC-tech-task-2#177]
![npmerror1](https://user-images.githubusercontent.com/55814483/82988967-92e0d700-9fbf-11ea-9cb9-603cb50017ac.PNG)

I am seeing the above error in CMD of my laptop while setting up my environment by following the setup pdf slide 50 for Task 2. 
Request anyone to solve my problem at the earliest so that I can complete this program. 

Thank you,

**Comment by Geno2208** [comment]
I got the same error. I just ignored it and continued with npm start. It works fine! :)

**Comment by srisubhashp** [comment]
Now, when I type NPM start, I am getting the below error. @Geno2208 Can you help me...
![npmstart2error](https://user-images.githubusercontent.com/55814483/83058423-f7328380-a01d-11ea-9005-66b81110de99.PNG)

I would be grateful to you...

**Comment by srisubhashp** [comment]
@Geno2208 I have tried your procedure as mentioned in this link https://github.com/insidesherpa/JPMC-tech-task-2/issues/174#issuecomment-634612840.

I am getting the below error. Can you please help me... 
![npmstart3error](https://user-images.githubusercontent.com/55814483/83059999-67420900-a020-11ea-919a-b83ec1cea52c.PNG)

**Comment by Geno2208** [comment]
@srisubhashp 
1. Remove package-lock.json file in the directory.
2. Run npm install and npm start again.
This worked for me! :)

**Comment by srisubhashp** [comment]
thanks a lot @Geno2208 for your Help. 
I am really happy now as this error is solved finally. 

I have one more request. If you are in any Insidesherpa common Facebook group for Computer Science students from JP Morgan, Deloitte,Accenture and KPMG companies...
Can you please kindly add me also in that group....

Thank you once again @Geno2208.

**Comment by denilaj** [comment]
i did the same process still i got the error. help me @Geno2208 @srisubhashp
