### ISSUE TITLE
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'

### ISSUE THREAD

**Issue by sushilca98** [insidesherpa/JPMC-tech-task-2#18]
I tried everything as explained in the closed ticket# 9 
![Error_JPMC](https://user-images.githubusercontent.com/53387282/70369556-6352dc80-1870-11ea-9638-705761b17ee5.PNG)
![Error_JPMC](https://user-images.githubusercontent.com/53387282/70369559-6948bd80-1870-11ea-9b57-8291c8487e43.PNG)

but still it gives me same result as
"NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1' "
Please help me asap and please let me know what I am doing wrong.
Please also explain me the proper way to run the server script.

**Comment by sushilca98** [comment]
![Server run](https://user-images.githubusercontent.com/53387282/70369573-b036b300-1870-11ea-97f8-21153c4aafa5.PNG)

**Comment by jbf-insidesherpa** [comment]
@sushilca98 you don't need to change anything in the `server.py` file. All you need to do is run it alongside the client app.

Note, running the server is via the command `python datafeed/server.py`. Do this in a separate command line and make sure you're running the command within the repository (i.e. your command line's present working directory is the repository). On a different command line, run the client via `npm start`. (this is assuming you're command line is also in the repository and you've done `npm install` already)

**Comment by sushilca98** [comment]
Hello Sir,
I tried the way you explained but when I run the command 
C:\Users\sushi\JPMC-tech-task-2>python datafeed/server.py
![Command run](https://user-images.githubusercontent.com/53387282/70377910-e99e0b80-18ce-11ea-8f33-8e2174b97b1c.PNG)
![command result](https://user-images.githubusercontent.com/53387282/70377916-fb7fae80-18ce-11ea-99e2-83b15583bd93.PNG)


 **Then it gives a response as** 
Traceback (most recent call last):
  File "datafeed/server.py", line 26, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser

**I also ran the separate command as**
C:\WINDOWS\system32>cd\Users\sushi\JPMC-tech-task-2

C:\Users\sushi\JPMC-tech-task-2>npm start

**Then I was able to go to Bank and Merge Co Task 2 but when I try to start streaming data it gives me same result as** 

NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'

Please check the screenshot and help me to get the result.

**Comment by sushilca98** [comment]
Never mind....after lot of try I was able to fix this issue.

**Comment by jbf-insidesherpa** [comment]
> Never mind....after lot of try I was able to fix this issue.

Glad you were able to fix the issue @sushilca98 . The issue you encountered regarding running the server script is also discussed in the slides in the trouble shooting section for the OS you're using. This has something to do with installing the missing python package i.e. `python date-util` via `pip`

**Comment by srisubhashp** [comment]
> Hello Sir,
> I tried the way you explained but when I run the command
> C:\Users\sushi\JPMC-tech-task-2>python datafeed/server.py
> ![Command run](https://user-images.githubusercontent.com/53387282/70377910-e99e0b80-18ce-11ea-8f33-8e2174b97b1c.PNG)
> ![command result](https://user-images.githubusercontent.com/53387282/70377916-fb7fae80-18ce-11ea-99e2-83b15583bd93.PNG)
> 
> **Then it gives a response as**
> Traceback (most recent call last):
> File "datafeed/server.py", line 26, in
> import dateutil.parser
> ImportError: No module named dateutil.parser
> 
> **I also ran the separate command as**
> C:\WINDOWS\system32>cd\Users\sushi\JPMC-tech-task-2
> 
> C:\Users\sushi\JPMC-tech-task-2>npm start
> 
> **Then I was able to go to Bank and Merge Co Task 2 but when I try to start streaming data it gives me same result as**
> 
> NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'
> 
> Please check the screenshot and help me to get the result.

I am facing the exact same error right now....
I also have the **dateuntil** error when the server starts
I do not know how to solve it.

Can anyone help me at the earliest...?
@sushilca98 @jbf-insidesherpa

**Comment by srisubhashp** [comment]
> @sushilca98 you don't need to change anything in the `server.py` file. All you need to do is run it alongside the client app.
> 
> Note, running the server is via the command `python datafeed/server.py`. Do this in a separate command line and make sure you're running the command within the repository (i.e. your command line's present working directory is the repository). On a different command line, run the client via `npm start`. (this is assuming you're command line is also in the repository and you've done `npm install` already)

Thank you very much @jbf-insidesherpa. I tried you suggestion and it started working
