### ISSUE TITLE
cannot do npm install on Mac OS Catalina

### ISSUE THREAD

**Issue by yumichelle** [insidesherpa/JPMC-tech-task-2#19]
![Screen Shot 2019-12-21 at 1 10 58 PM](https://user-images.githubusercontent.com/27922550/71311966-b93c8e00-23f3-11ea-8e44-ba4bc1d43c21.png)
this is the errors I got, which makes me think it's related to python? I have Python 2.7.16 and
`npm -v
6.9.0
node -v
v12.6.0
`

**Comment by jbf-insidesherpa** [comment]
@yumichelle Have you tried doing the suggested solution in this slide:
![image](https://user-images.githubusercontent.com/54832297/71332991-3e9a7c80-2573-11ea-8ecb-952b4c1db68f.png)

([slide 25/95](https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v8.pdf))
What you need to try here is the npm config set python <path to executable/binary of python in your system>
To find out where your python is installed in your mac you can use the which command i.e. which python

Hope this helps.

**Comment by yumichelle** [comment]
Thank you for the reply. I've done what you said but it still didn't work. I also tried to do `python datafeed/server.py` but I got an error when I didn't last time.
![Screen Shot 2019-12-23 at 12 05 12 PM](https://user-images.githubusercontent.com/27922550/71370721-c5a02280-257c-11ea-991a-4535740d94bf.png)
![Screen Shot 2019-12-23 at 12 05 19 PM](https://user-images.githubusercontent.com/27922550/71370723-c5a02280-257c-11ea-9fef-03c11c2f2be9.png)
![Screen Shot 2019-12-23 at 12 05 26 PM](https://user-images.githubusercontent.com/27922550/71370724-c5a02280-257c-11ea-9fd6-8eea104d20bc.png)
![Screen Shot 2019-12-23 at 12 05 33 PM](https://user-images.githubusercontent.com/27922550/71370725-c638b900-257c-11ea-92fa-def699086f67.png)
![Screen Shot 2019-12-23 at 12 05 51 PM](https://user-images.githubusercontent.com/27922550/71370726-c638b900-257c-11ea-9887-4313a583681a.png)
![Screen Shot 2019-12-23 at 12 06 17 PM](https://user-images.githubusercontent.com/27922550/71370727-c638b900-257c-11ea-978a-67f7807c4103.png)

**Comment by jbf-insidesherpa** [comment]
@yumichelle is this all resolved now? Please feel free to reopen the ticket if it's still revelant. Closing it for now
