### ISSUE TITLE
npm installation error

### ISSUE THREAD

**Issue by Sakshi0112** [insidesherpa/JPMC-tech-task-2#199]
This is what I'm facing. Please suggest solutions to resolve it. Thank you for your cooperation.
![Screenshot (591)](https://user-images.githubusercontent.com/43519257/83355005-3ba18480-a37a-11ea-8c49-2f83dddf4012.png)

**Comment by Siddharth1006** [comment]
Its connected to python 37 in yours. Try connecting it python 2.7
"C:\Users\Python27" Try something like this or change the path to location where python27 is present in your computer. I use linux. So, i am facing a bit difficulty helping you. Try google searching about this problem. Or you can find a solution in the "troubleshooting problems" in JPMorgan Setup environment pdf. They have a Github post link specific to your issue.

**Comment by Sakshi0112** [comment]
> Its connected to python 37 in yours. Try connecting it python 2.7
> "C:\Users\Python27" Try something like this or change the path to location where python27 is present in your computer. I use linux. So, i am facing a bit difficulty helping you. Try google searching about this problem. Or you can find a solution in the "troubleshooting problems" in JPMorgan Setup environment pdf. They have a Github post link specific to your issue.

Thank you for your help!

**Comment by Siddharth1006** [comment]
Glad I could be of some help!
