### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by adagloria** [insidesherpa/JPMC-tech-task-2#20]
Everytime I attempt running the "npm -v" command, I get this error: "cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'"
I have tried uninstalling nvm and cleaning up previous nodejs  and npm files but still does not work

![Capture](https://user-images.githubusercontent.com/22063438/71450996-6ce3ac00-276d-11ea-815b-fae8a63e67e6.JPG)

**Comment by jbf-insidesherpa** [comment]
@adagloria when you installed `nvm`, in which directory did you choose to install it. It maybe because you installed it in a directory that has a space in its name. Windows has a problem like that.
