### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by akrutikhandelwal** [insidesherpa/JPMC-tech-task-2#204]
I'm working on Windows. after doing all the steps as mentioned, I'm getting an error after typing npm install

![Annotation 2020-06-02 202025](https://user-images.githubusercontent.com/43274159/83534511-923fc780-a50e-11ea-95e7-518de1a347e0.png)

**Comment by dheerajodha** [comment]
Hi @akrutikhandelwal please check previously closed issues, this is a common problem.
Also, you are required to run npm install from the inside the folder where you cloned your JPMC-tech-task project.

**Comment by akrutikhandelwal** [comment]
HI,
I'm still getting an error

**Comment by akrutikhandelwal** [comment]
Yes

**Comment by akrutikhandelwal** [comment]
![npm1](https://user-images.githubusercontent.com/43274159/83750691-46faf580-a683-11ea-8a95-302eeb6ce789.png)
I cloned it inside the repository too and still there's an error

**Comment by akrutikhandelwal** [comment]
I got it.  looked at previous closed issues and it worked.
Thank You :)

**Comment by dheerajodha** [comment]
@akrutikhandelwal That's great! My pleasure :)

**Comment by akrutikhandelwal** [comment]
Hi,
I've come here with another small doubt.
I'd be grateful if you could help

**Comment by akrutikhandelwal** [comment]
Hi,
I've come here with a small doubt.
I'd be grateful if you could help.
what is the repository name I should add while making the patch file?

**Comment by dheerajodha** [comment]
@akrutikhandelwal I'm not if I understood you correctly, correct me if I'm wrong.
Inside InsideSherpa guide to make a patch file :
 
"Fire up a terminal, **enter** **the** **repository** (_Is this what you are asking about?_) via the terminal you opened (via the cd<repo_name_here> aka change directory command) and do the following commands(one line, one command)"

**Comment by akrutikhandelwal** [comment]
yes yes, I'm asking about the exact same thing

**Comment by dheerajodha** [comment]
@akrutikhandelwal first of all, patch file is somewhat analogous to submission of your homework to your professors for grading, in order to get correct grades you need to submit the exact assignment on which you worked on right? Not an one year old assignment haha 

So what I'm trying to say is you are supposed to enter the **path of the JPMC task folder wherein you made changes** and then run patch commands so your changes are recorded correctly. I hope that makes sense.

**Comment by akrutikhandelwal** [comment]
I had entered the path where I made changes but I was getting an error
message. So, I thought I was going wrong.
You can check the see screenshot below.

**Comment by dheerajodha** [comment]
I can't find your attachment, can you attach it again?

**Comment by akrutikhandelwal** [comment]
I realised the issue, I had to use "" instead '' when typing create patch
file.
Thank you for your help :)

**Comment by dheerajodha** [comment]
Yes! no problem.
