### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by vvv-99** [insidesherpa/JPMC-tech-task-2#214]
<img width="630" alt="Screenshot 2020-06-07 at 20 15 16" src="https://user-images.githubusercontent.com/63586183/83968726-bda32780-a8fd-11ea-8a80-2fcfc3163908.png">

Hi, I have encountered the error above and looking for the solutions. 
May I ask for some help please? Thanks in advanced.

**Comment by Kritika37** [comment]
hey, just change your directory where you have cloned the JPMC task2 and install npm in that directory.
Also use npm init to set the description and repository field for the project

**Comment by vvv-99** [comment]
@Kritika37 Thank you very much, it helped a lot!

**Comment by sejalkhannaa** [comment]
![Screenshot 2020-06-11 at 4 34 12 PM](https://user-images.githubusercontent.com/63471911/84379599-b7fe5800-ac03-11ea-856c-39f914c17a1a.png)
can you please guide me with this!!!
