### ISSUE TITLE
Error Module not found: Can't resolve 'react' in 'C:\Users\username\JPMC-tech-task-3-PY3\src'

### ISSUE THREAD

**Issue by Deepak-1373** [insidesherpa/JPMC-tech-task-2#215]
![Screenshot (150)](https://user-images.githubusercontent.com/61752151/84004954-f8eb3800-a989-11ea-8588-5ce93f70c8fe.png)

**Comment by Deepak-1373** [comment]
I am getting this error what should i do to fix this?

**Comment by ns-github14** [comment]
Same error :(

**Comment by Deepak-1373** [comment]
I got the solution.
First npm i @finos/perspective
Second npm install
Third npm audit fix
Fourth npm start
The problem will be solved

**Comment by samiran32** [comment]
this is not worked, do you have any other solution for this problem

**Comment by wayfarerprism** [comment]
@samiran32 same ...
did u get the solution for this???

**Comment by Deepak-1373** [comment]
solved
