### ISSUE TITLE
Different App.tsx

### ISSUE THREAD

**Issue by neissacodes** [insidesherpa/JPMC-tech-task-2#22]
While editing the App.tsx code I realized that I have a different code than the one in the guide and now I do not know to properly edit it. 
![App JPMC](https://user-images.githubusercontent.com/47401355/71642419-befa6500-2c78-11ea-948c-dda348c18a42.PNG)

**Comment by jbf-insidesherpa** [comment]
@neissacodes I've already responded here: https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/28

closing this now...
