### ISSUE TITLE
Graph is not appering at the end of the task.

### ISSUE THREAD

**Issue by Jeet-Prajapati** [insidesherpa/JPMC-tech-task-2#222]
![Screenshot (46)](https://user-images.githubusercontent.com/53653227/84561817-37f40180-ad6d-11ea-90f2-0b3ebdbb348a.png)

- I have done the environment setup successfully.

- And did all the changes to the App.tsx and Graph.tsx file in VSC.After all the changes the graph is not appearing on the screen,only start streaming button appears.

- On clicking that button only 3 dots are displaying.

- ON the other side where the server is running there the queries are getting generated.

- I tried to open this on three different browsers i.e. chrome,mozilla firfox and microsoft edge but not getting the output.

- Please provide some solution ,I am stuck.

**Comment by parthdama** [comment]
this issue got resolved??, mine too same problem@Jeet-Prajapati

**Comment by Jeet-Prajapati** [comment]
Yes,I went back and took new app.tsx and graph.tsx file and made changes again and it worked.....!tell me when you are done!

**Comment by parthdama** [comment]
> Yes,I went back and took new app.tsx and graph.tsx file and made changes again and it worked.....!tell me when you are done!

**Comment by parthdama** [comment]
Yaa, i did the same thing, it got resolved, thanks bro @Jeet-Prajapati

**Comment by aruvasrikesh0702** [comment]
> Yaa, i did the same thing, it got resolved, thanks bro @Jeet-Prajapati

can you keep the changes made in graph.tsx file
