### ISSUE TITLE
Error when clicked on 'Start Streaming Data'

### ISSUE THREAD

**Issue by sahanabela** [insidesherpa/JPMC-tech-task-2#23]
I am using Windows (am on a chrome browser) and successfully installed npm for task 2. I typed "npm start" in the command prompt and it said that it "Compiled Successfully!" It then pulled up the browser to a page with a button that says "Start Streaming Data." I clicked on the button and it gave me an error as shown below. I'm not sure how to go about fixing this? Thank you!

![task2help1](https://user-images.githubusercontent.com/55221478/72094121-5431d500-32db-11ea-88dc-40c67034db34.JPG)
![task2help](https://user-images.githubusercontent.com/55221478/72094122-5431d500-32db-11ea-9b5b-c7c06955b8dc.JPG)

**Comment by jbf-insidesherpa** [comment]
@sahanabela you probably didn't start the server script that's why the client couldn't request any data. Make sure to run **python datafeed/server.py** first from the root of the repository then you can run the **npm start** command again

**Comment by sahanabela** [comment]
I did that and it is still giving me the same error even though it says it compiled successfully.[
![Capture](https://user-images.githubusercontent.com/55221478/73308131-39b99000-41e5-11ea-82e6-863c43898439.JPG)
](url)

**Comment by sahanabela** [comment]
It works now, for some reason. I did not change anything so not exactly sure what happened haha. Thanks!
