### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by klegan** [insidesherpa/JPMC-tech-task-2#230]
Initially, I was having an issue with npm install, so I followed some of the other troubleshooting solutions. I downloaded the node_modules and replaced it with the original node_modules folder inside the JPMC-tech-task-2 folder. Then I tried running npm start again but now I am getting this new error and was wondering if anyone knows how to fix this? 
<img width="564" alt="Screen Shot 2020-06-18 at 2 49 53 PM" src="https://user-images.githubusercontent.com/54511972/85065539-f9968200-b172-11ea-801e-a58744b8a292.png">

**Comment by shamaz332** [comment]
You can skip npm install step by downloading the node_modules from https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view And replace the node_modules folder in JPMC-tech-task-2-PY3.
then run npm start
if it shows error for react-scripts then run this command npm i -g react-scripts
then runnpm start
that helped for me.
