### ISSUE TITLE
Type error: Cannot find module '@jpmorganchase/perspective'. TS2307 

### ISSUE THREAD

**Issue by lunakoj** [insidesherpa/JPMC-tech-task-2#24]
I checked the nom start like advised on another issue report and it didn't help as npm shows to start up quite well 
![localhost 3000](https://user-images.githubusercontent.com/58075282/72665520-40881c00-3a09-11ea-8659-65e54cf19717.png)

**Comment by jbf-insidesherpa** [comment]
@lunakoj you're probably getting that error because **npm install** wasn't completing successfully on your end. Can you attach a screenshot of what errors you're getting on your console after you run **npm install**? The setup slides also discuss the workarounds for most issues a user might get when running **npm install**

**Comment by lunakoj** [comment]
Thank you for your response.
Attached are the error screen while installing NPM as requested.
I look forward to a resolution so I can carry on with the task.
Warm Regards 
Olisa Okeke
    On Monday, January 27, 2020, 12:29:06 AM UTC, jbf-insidesherpa <notifications@github.com> wrote:  
 
 
@lunakoj you're probably getting that error because npm install wasn't completing successfully on your end. Can you attach a screenshot of what errors you're getting on your console after you run npm install? The setup slides also discuss the workarounds for most issues a user might get when running npm install

**Comment by debarshikundu** [comment]
I am actually getting the same error :(

![image](https://user-images.githubusercontent.com/8769572/78961578-91af2580-7ab7-11ea-839a-793dbed7b36e.png)

**Comment by surbhi1005** [comment]
Hi debarshikundu, did you find any solution for the problem since I have the same problem and can't resolve it.

**Comment by tanay-nagarsheth** [comment]
did anyone find the solution to this? I have installed npm correctly , everything is right but this error wont stop showing Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

**Comment by PoojaRani24** [comment]
Make sure you are using the correct node version. Using `nvm use v11.0.0` followed by `sudo npm install` worked for me

**Comment by yash-kedia** [comment]
nvm use v11.0.0 is not working for me

exit status 1: 'C:\Users\Yash' is not recognized as an internal or external command,
operable program or batch file.

can anyone tell me how to resolve this error

**Comment by estradanicolas** [comment]
I have also ran into this error. Any ideas on the solution?

**Comment by TanishB** [comment]
You can skip npm install step by downloading the node_modules from [here](https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view). And replace the node_modules folder inside JPMC-tech-task-2-PY3 with the one you downloaded from the link mentioned above.
Now you just need to execute npm start!

**Comment by PrajolADSethi** [comment]
@TanishB I tried your method but its not working for me Can you tell me if i should uninstall anything more than the npm ? Earlier I followed the steps given in the instruction manual

**Comment by TanishB** [comment]
@PrajolADSethi You don't need to uninstall anything. By replacing node_modules you are skipping the npm install step, that's it.

**Comment by PrajolADSethi** [comment]
Okay Thank you @TanishB but still changing the node folder didn't work for me

**Comment by akshatgupta1019** [comment]
i am facing the same issue! did anyone got the solution?

**Comment by ikshitjalan** [comment]
i am facing this same issue too
How to resolve it?

**Comment by sujith8897** [comment]
same issue please help

**Comment by KILLERCAFER** [comment]
same issue, can't get a response from the online help!

**Comment by sujith8897** [comment]
I got the answer to the issue..
Download node modules file from the comments above and then `npm install react-scripts` by using this i am able to solve this

**Comment by RudraPaksh** [comment]
Failed to compile
C:/Users/asus1/JPMC-tech-task-2/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
    5 | 
This error occurred during the build time and cannot be dismissed.



i am getting this error please tell me how can i resolve this error

**Comment by RudraPaksh** [comment]
same issue, can't get a response from the online help!

**Comment by gthe1andonly** [comment]
I don't know if this will help anyone, but I went to the node js site and downloaded it as if i was installing a basic application on my computer. Then i did the npm install and nmp start agaain.

**Comment by sumthegreat** [comment]
I am also having the same issue.

**Comment by deepaa28** [comment]
same issue, please help!

**Comment by gthe1andonly** [comment]
https://nodejs.org/en/download/

please try to download node js this way and see if it helps you. Then go through the process again as shown on the slides.

**Comment by parthsikka** [comment]
@TanishB rightly said. Try downloading the node_modules folder from [here](https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view) and replace it with the one in your Task 2 folder.
Now directly jump to `npm start`

**Comment by Prannesh45** [comment]
For all the users, who have the error
Just go to visual studio 2017 and run VS 2017 terminal
Once you enter, move to the directory where you have saved JPMC-tech-task
Delete the folder node_modules
Being in the 2017 VS command prompt, run "npm install " 
It will take around 153 MB download
And then run "npm start", it will work

**Comment by divyanshu450** [comment]
This option really worked for me. I don’t know exactly what the problem was but it was definitely not related with setting up path environments in my case.

**Comment by govilharsh** [comment]
Can we use visual studio 2019 ?

**Comment by Prannesh45** [comment]
Your nvm version and this vs should match, so node_gyp error can be prevented. 
So we can't use it. 
If we use, node_gyp error might occur.

**Comment by govilharsh** [comment]
Thanx a lot !!! Its working now.

**Comment by aman-5757** [comment]
> nvm use v11.0.0 is not working for me
> 
> exit status 1: 'C:\Users\Yash' is not recognized as an internal or external command,
> operable program or batch file.
> 
> can anyone tell me how to resolve this error

Hii try this --> cd/Users/ --> then run dir /x   --> You will get something like YASH~1 (In my case it was AMANSR~1) --> then try again using the same eg. C:\Users\YASH~1 instead of C:\Users\YASH

**Comment by aman-5757** [comment]
![image](https://user-images.githubusercontent.com/47601036/82012818-775bff00-9696-11ea-99ff-38848002a499.png)


I am facing error in command npm install --> can someone please help me!

**Comment by vaisakh-123** [comment]
[](url)https://drive.google.com/uc?id=1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t&export=download

Download the zip file from the link.Extract it to JPMC-tech-task-2-PY3. Run 'npm start' in cmd.
**No need to use 'npm install' in this case**.

**Comment by Nakzz** [comment]
> https://drive.google.com/uc?id=1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t&export=download
> 
> Download the zip file from the link.Extract it to JPMC-tech-task-2-PY3. Run 'npm start' in cmd.
> **No need to use 'npm install' in this case**.

Not sure if that's a good idea, at least for developing in a project that could be used in different devices. 

`npm install` installs the packages and pre-reqs for those packages depending on the machine you are using. Although you are able to solve it by pasting someone else's node_modules files, you shouldn't want to just paste it in your directory. That's a major security threat.

I was able to solve the problem with the following

```
npm install -g node-gyp node-pre-gyp
npm install --unsafe-perm
```

But this isn't the solution for all the people who posted their screens or their error messages. Some people are having permission issue and some are having issue with your npm not being able to find your python executable.

**Comment by Anamika0101** [comment]
![image](https://user-images.githubusercontent.com/65092736/82126557-374a6880-97cb-11ea-82f2-0288312433f2.png)
Using node_modules provided here, i tried npm start and now this is the error. I am trying to work on this since yesterday and there is always some error.

**Comment by gthe1andonly** [comment]
run npm start from the task folder and not the node modules folder. You might still get a dfferent error though

**Comment by Anamika0101** [comment]
I did try that also, same error exist.

**Comment by Prannesh45** [comment]
Delete node_modules and try again with setting VS terminal to 2017
Being in the 2017 VS command prompt, run "npm install "
It will take around 153 MB download
And then run "npm start", it will work
this error is mostly because of your python version linkage with Vs Version

**Comment by Anamika0101** [comment]
> Delete node_modules and try again with setting VS terminal to 2017
> Being in the 2017 VS command prompt, run "npm install "
> It will take around 153 MB download
> And then run "npm start", it will work
> this error is mostly because of your python version linkage with Vs Version

![image](https://user-images.githubusercontent.com/65092736/82128108-14718180-97d6-11ea-8d7b-08162e89e092.png)
![image](https://user-images.githubusercontent.com/65092736/82128099-0a4f8300-97d6-11ea-9bc5-6776991275a7.png)
I tried and again there is problem!

**Comment by Prannesh45** [comment]
I would like you to try out this
prebuild-install || node-gyp, try this command
and then check in the path directory whether the python path(where you have installed python) is included
Before set can be achieved by searching path in start menu and selecting edit the system env variables and select environment variables and select path in the second list box. Select the path and add the python.exe location

**Comment by Anamika0101** [comment]
> I would like you to try out this
> prebuild-install || node-gyp, try this command
> and then check in the path directory whether the python path(where you have installed python) is included
> Before set can be achieved by searching path in start menu and selecting edit the system env variables and select environment variables and select path in the second list box. Select the path and add the python.exe location

Still not working

**Comment by eakarakaplan** [comment]
> For all the users, who have the error
> Just go to visual studio 2017 and run VS 2017 terminal
> Once you enter, move to the directory where you have saved JPMC-tech-task
> Delete the folder node_modules
> Being in the 2017 VS command prompt, run "npm install "
> It will take around 153 MB download
> And then run "npm start", it will work

I worked for me. Thanks.

**Comment by yasharth291** [comment]
> nvm use v11.0.0 is not working for me
> 
> exit status 1: 'C:\Users\Yash' is not recognized as an internal or external command,
> operable program or batch file.
> 
> can anyone tell me how to resolve this error

It is because of the space coming in your path.

**Comment by samrojo** [comment]
> You can skip npm install step by downloading the node_modules from [here](https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view). And replace the node_modules folder inside JPMC-tech-task-2-PY3 with the one you downloaded from the link mentioned above.
> Now you just need to execute npm start!

Actually just adding the @jpmorganchase folder to the node_modules will do the work. Thanks for it!

**Comment by neelabhkrishna** [comment]
npm i --save @finos/perspective-viewer @finos/perspective-viewer-d3fc @finos/perspective-viewer-datagrid

**Comment by PrajolADSethi** [comment]
Hello so some weeks back I was facing the same issues of react and have overcome it and would like to share with you all 
Note : 
1.Reclone the repository you are working on and delete the previous one 
2. If using windows use the directory 
C:/Users/public/<xyz_folder>/<repository>
3. Don't use space in your file name 
4. Verify that you are using python version 2.7 or 3+ ; node version 6 ; nvm version 1.1.8 or a nearby one , npm version 11.0.0 and visual studios 2017 
5. Make sure that while installing visual studios you clicked all options as guided in the ppt .
Now, 
After these verifications let's first setup the server side : 
1.Open CMD 
2. change directory to where your repository is then make sure you are in the repository .
3 . Run the  python3 datafeed/server3.py command 
(If you get a dateutil error then either you write python3 as python itself and run still not working and you have pip installed already then install wheel package and then run )
After the port 8080 gets set now client side :
1.Open CMD (Administrator)
2. cd to desired location
3. check nvm version you installed 
4. Follow the steps as in ppt 
5. Use nvm 11.0.0
6.config...2017 command
7.npm start 
Now if you are running into same type script errors 
1 use the install command again 
2. After a while it may show you steps to fix audits run that and again force audit steps 
3. Run 5,6,7 step again still not working see if it is asking to install some packages like bootstrap and so 
4. Again install fix audits and rerun this time it may get no compilation error and you might see the blue button on the local host page .

I hope this steps may help you as it worked in my case so All the best 👍

**Comment by FedericoRead** [comment]
> You can skip npm install step by downloading the node_modules from [here](https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view). And replace the node_modules folder inside JPMC-tech-task-2-PY3 with the one you downloaded from the link mentioned above.
> Now you just need to execute npm start!

Thanks man, downloading the zip file worked for me... after doing a few extra steps. Apparently, if I try to copy the node_modules folder (from the .zip folder) into the JPMC-tech-task-2 folder it takes an eternity (literally, while copying it my computer said it would take more than a day then stopped at 10%). I just copied the zip folder, deleted the original node_modules folder, then moved the new node_modules folder (inside the zip file) into the JMPC-tech-task-2 directory.

However, for some reason it won't go through because it's complaining about react-scripts not being an internal or external command or whatever, so what I did was delete the original react-scripts folder in the new node_modules folder then installed react-scripts again (npm i react-scripts). This fixed the type error, but then it complained about not finding a require-from-string module. So I installed that in a similar fashion (npm install --save require-from-string), did npm install, and then npm start, and then it worked! I have been struggling on this for weeks and I'm glad I was finally able to fix it.

**Comment by Nakul4998** [comment]
![20200612_213107](https://user-images.githubusercontent.com/58903446/84522671-b2cd0600-acf4-11ea-9ead-189c65cce828.jpg)
Using node_modules provided here, i tried npm start and now this is the error. I am trying to work on this since yesterday and there is always some error.

**Comment by samrojo** [comment]
> ![20200612_213107](https://user-images.githubusercontent.com/58903446/84522671-b2cd0600-acf4-11ea-9ead-189c65cce828.jpg)
> Using node_modules provided here, i tried npm start and now this is the error. I am trying to work on this since yesterday and there is always some error.

Hace you tried "npm start" instead of "react-scripts start"?, Don't really know if that would work, I was using it on windows. Or try using sudo

**Comment by buyrenagesh** [comment]
Failed to compile
C:/Users/buyre/JPMC-tech-task-3-PY3/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import { DataManipulator } from './DataManipulator';
    5 | import './Graph.css';
This error occurred during the build time and cannot be dismissed.

**Comment by 7Kushal** [comment]
You can skip npm install step by downloading the node_modules from [https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view](url) And replace the node_modules folder in JPMC-tech-task-2-PY3.
then run `npm start `
if it shows error for react-scripts then run this command `npm i -g react-scripts  `
then run` npm start `
that helped for me.

**Comment by srinath-nanduri** [comment]
@7Kushal Thanks.
It worked without any error.

**Comment by shamaz332** [comment]
> You can skip npm install step by downloading the node_modules from [here](https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view). And replace the node_modules folder inside JPMC-tech-task-2-PY3 with the one you downloaded from the link mentioned above.
> Now you just need to execute npm start!

thanks this work for me

**Comment by SuhasPatlolla** [comment]
@jbf-insidesherpa I have made changes successfully and there are no errors but when i press START STREAM DATA I can' t see any graph displayed...

**Comment by rashadwalcott** [comment]
> I got the answer to the issue..
> Download node modules file from the comments above and then `npm install react-scripts` by using this i am able to solve this

This worked for me. Thank you!

**Comment by FutureHet** [comment]
> > You can skip npm install step by downloading the node_modules from [here](https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view). And replace the node_modules folder inside JPMC-tech-task-2-PY3 with the one you downloaded from the link mentioned above.
> > Now you just need to execute npm start!
> 
> Actually just adding the @jpmorganchase folder to the node_modules will do the work. Thanks for it!

Sorry, I couldn't get it.
Can you explain what exactly you are asking?

**Comment by FutureHet** [comment]
I am not able to solve the npm start problem.
Can anyone help me.
I tried everything mentioned above, I also downloaded new module package and replaced it by the previous one
but still getting the same error.

**Comment by srinath-nanduri** [comment]
Actually when you just delete the 'node_modules' folder and replace it with the new one which you can download at the link given above(as well as in troubleshooting of setup pdf ), you are leaving .json files which have cache from previous commands of npm.

You have to clear the cache or if you dont know the node commands , simply follow these steps:

1. Delete the JPMC-tech-task-2-py3/JPMC-tech-task-2 folder from your C Drive.
2. Use git clone command again so you have fresh .json files
3. Instead of npm install,  copy the node_modules folder from the zip file you downloaded.(make sure its name is node_modules).
4. Check if it has @jpmorganchase folder. 
5. If yes then start your server in an administrator cmd
6. Run 'npm start' in a normal cmd in the JPMC-tech-task-2-py3/JPMC-tech-task-2 folder.
(Make sure you are in that folder when you run the scripts of server and start npm)
(This is how you hange directory: cd \Users\<admin>\JPMC-tech-task-2-py3)
At <admin> type your own administrator name.

This steps gave me the proper output

**Comment by FutureHet** [comment]
I followed the steps you suggested but after doing that when I run npm start
I am getting error as 

> bank-merge-co-task-2@0.1.0 start C:\Users\admin\JPMC-tech-task-2-PY3
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2020-06-28T10_20_48_028Z-debug.log

what should I do now.

**Comment by 7Kushal** [comment]
See my solution above @FutureHet

**Comment by FutureHet** [comment]
Okay I run the command npm install and when i check the folder named @jpmorganchase in the node_modules 
so I just copy paste that folder from the node_modules folder which link was given by you.
Now it is working .
Thanks a lot.
@7Kushal and @srinath-nanduri

**Comment by whoscdy** [comment]
I solved this by removing package-lock.json, 
then run npm install
then npm start works

**Comment by irisshakya** [comment]
> You can skip npm install step by downloading the node_modules from [here](https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view). And replace the node_modules folder inside JPMC-tech-task-2-PY3 with the one you downloaded from the link mentioned above.
> Now you just need to execute npm start!

this works if the it shows react error asking to download dependencies.

**Comment by cheesken** [comment]
Mine is WORKING and so I thought I will share the way I did it:
1) When cloning from git, clone the 2.7 version. It will save you a lot of trouble down the way since a lot of nvm dependencies are with python 2.7
2) Go to terminal and `cd` into the folder
3) `xcode-select --install`
4) `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash`
5) copy the two lines from "export NVM_DIR" to "# This loads nvm" 
check https://www.youtube.com/watch?v=Bhu7p7sHMaQ at 1:17 time for more information 
6) `sudo vi ~/.bash_profile`
7) paste the two lines here
8) `~/.bash_profile`
9) `nvm --version`
It should show the version
10) `nvm install v11.0.0`
11) `nvm use v11.0.0`
12) npm install
13) npm start

THIS SHOULD WORK
HOPE IT HELPS

**Comment by Punit29** [comment]
> npm i --save @finos/perspective-viewer @finos/perspective-viewer-d3fc @finos/perspective-viewer-datagrid

Thanks this worked for me.
Those who are trying this just run this command in cmd and change the path from "@jpmorganchase/perspective" to "@finos/perspective" in the error line.

Hope It Helps.

**Comment by veersan** [comment]
Download the node_modules file from slide 92 and 
The @jpmorgan file itself wasnt there in the nodes_module
So I copied that from the node files (downloaded from slide 92).
The error does'nt show anymore.
Try this.

**Comment by jpmorgan** [comment]
> Download the node_modules file from slide 92 and
> The @jpmorgan file itself wasnt there in the nodes_module
> So I copied that from the node files (downloaded from slide 92).
> The error does'nt show anymore.
> Try this.

Hi just FYI everytime you quote @jpmorgan you are sending a notification to me as a mention.. This "insidesherpa" github has done this many many times. 

Just thought I'd let you know!

**Comment by akirpach** [comment]
> Actually when you just delete the 'node_modules' folder and replace it with the new one which you can download at the link given above(as well as in troubleshooting of setup pdf ), you are leaving .json files which have cache from previous commands of npm.
> 
> You have to clear the cache or if you dont know the node commands , simply follow these steps:
> 
> 1. Delete the JPMC-tech-task-2-py3/JPMC-tech-task-2 folder from your C:/admin.
> 2. Use git clone command again so you have fresh .json files
> 3. Instead of npm install,  copy the node_modules folder from the zip file you downloaded.(make sure its name is node_modules).
> 4. Check if it has @jpmorganchase folder.
> 5. If yes then start your server in an administrator cmd
> 6. Run 'npm start' in a normal cmd in the JPMC-tech-task-2-py3/JPMC-tech-task-2 folder.
>    (Make sure you are in that folder when you run the scripts of server and start npm)
>    (This is how you hange directory: cd \Users<admin>\JPMC-tech-task-2-py3)
>    At  type your own administrator name.
> 
> This steps gave me the proper output

I followed exact steps as you described. However, when I run my **npm start** it outputs the following: 
![tech3](https://user-images.githubusercontent.com/60857086/105126644-36ca4600-5aad-11eb-99bd-ef8990fc3ba0.png)

**Comment by akirpach** [comment]
> I solved this by removing package-lock.json,
> then run npm install
> then npm start works

I tried your solution and when I input **npm start** it produces this:
![tech4](https://user-images.githubusercontent.com/60857086/105127779-8b6ec080-5aaf-11eb-9323-1368e61c7deb.png)

**Comment by AkhidenorH** [comment]
> Actually when you just delete the 'node_modules' folder and replace it with the new one which you can download at the link given above(as well as in troubleshooting of setup pdf ), you are leaving .json files which have cache from previous commands of npm.
> 
> You have to clear the cache or if you dont know the node commands , simply follow these steps:
> 
> 1. Delete the JPMC-tech-task-2-py3/JPMC-tech-task-2 folder from your C:/admin.
> 2. Use git clone command again so you have fresh .json files
> 3. Instead of npm install,  copy the node_modules folder from the zip file you downloaded.(make sure its name is node_modules).
> 4. Check if it has @jpmorganchase folder.
> 5. If yes then start your server in an administrator cmd
> 6. Run 'npm start' in a normal cmd in the JPMC-tech-task-2-py3/JPMC-tech-task-2 folder.
>    (Make sure you are in that folder when you run the scripts of server and start npm)
>    (This is how you hange directory: cd \Users<admin>\JPMC-tech-task-2-py3)
>    At  type your own administrator name.
> 
> This steps gave me the proper output

waoh! this is it. it works perfectly. thank you so much

**Comment by KareemSalem7** [comment]
> You can skip npm install step by downloading the node_modules from [https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view](url) And replace the node_modules folder in JPMC-tech-task-2-PY3. then run `npm start ` if it shows error for react-scripts then run this command `npm i -g react-scripts ` then run`npm start` that helped for me.

I still get an error that says 'react-scripts' is not recognized as an internal or external command,
operable program or batch file. any help??

**Comment by KareemSalem7** [comment]
I realised my nodes module folder was nested for some reason that fixed it

**Comment by loannejee** [comment]
What worked for me to install react, react-dom and @finos/perspective properly without "Failed to Compile" showing up:
Enter all at once:
1. npm install react react-dom @finos/perspective --save
2. Go to the Graph.tsx file and replace
• import { Table } from **'@jpmorganchase/perspective'**;
with
• import { Table } from **'@finos/perspective'**;

**Comment by iamsahil08** [comment]
> > You can skip npm install step by downloading the node_modules from [https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view](url) And replace the node_modules folder in JPMC-tech-task-2-PY3. then run `npm start ` if it shows error for react-scripts then run this command `npm i -g react-scripts ` then run`npm start` that helped for me.
> 
> I still get an error that says 'react-scripts' is not recognized as an internal or external command, operable program or batch file. any help??

Try installing latest version of react-scripts by running `npm i react-scripts@latest`.

Follow these steps for react-scripts not recognized:
1. Replace node modules in directory with [this](https://drive.google.com/u/0/uc?id=1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t&export=download).
2. Run cmd as administrator and run `npm i react-scripts@latest` in the directory.
3. Run `npm start`
