### ISSUE TITLE
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

### ISSUE THREAD

**Issue by abhishekthakur0** [insidesherpa/JPMC-tech-task-2#248]

**Comment by goku9313** [comment]
The best solution of this problem is instead of wasting time on npm install 
download the zip file https://drive.google.com/uc?id=1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ&export=download
and run npm start along side server.py

**Comment by SarveshMohan89** [comment]
@goku9313 what do you mean by run alongside? Do you mean save the contents in the datafeed folder and first run server.py and then run use nvm config and nvm start ?

**Comment by goku9313** [comment]
Yes first run server.py  in one command prompt and datafeed in another command prompt

**Comment by abhishekthakur0** [comment]
@goku9313 your solution worked for me. Thank You
