### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by aishwaryarajesh** [insidesherpa/JPMC-tech-task-2#256]
I have several warnings but not sure how to resolve them. I have chrome installed on my Mac and have been able to pull up localhost3000: in past projects but it hasn't been working now. I tried changing 8080 to 8085 and theres no difference. I've attached screenshots with the warnings and errors as well. 

<img width="1224" alt="npm install" src="https://user-images.githubusercontent.com/44328644/86679435-90649a80-bfcb-11ea-80fc-067507b55bce.png">
<img width="1234" alt="npm start" src="https://user-images.githubusercontent.com/44328644/86679441-90fd3100-bfcb-11ea-9f7f-d6ab3b116187.png">

**Comment by binnydara** [comment]
hey hi @aishwaryarajesh  did you get the error resolved ? if you did how did you resolve it .. having the same error

**Comment by aishwaryarajesh** [comment]
@binnydara this error was due to not have perspective downloaded (node_modules folder), so I downloaded a new set of node_modules which is on one of the troubleshooting slides and then it worked!
