### ISSUE TITLE
Sytax error

### ISSUE THREAD

**Issue by laimenn** [insidesherpa/JPMC-tech-task-2#257]
<img width="776" alt="Capture" src="https://user-images.githubusercontent.com/49475852/86904173-e576ec80-c142-11ea-9d79-ac0636a781d6.PNG">

I got this error, but there there is already a single quote ' at the end.

**Comment by christopherkalfas** [comment]
I think the issue is using the single quote for the second argument.  You show use backticks 
```element.setAttribute('aggregates', `{"stock": "distinct count"}`)```

Another issue, you've misspelled 'distinct' on line 56. You spelled it 'distict'

**Comment by christopherkalfas** [comment]
Actually I take that back! I think it's just the spelling issue. single quotes should be good.
