### ISSUE TITLE
npm install issue 

### ISSUE THREAD

**Issue by Curtly4** [insidesherpa/JPMC-tech-task-2#26]
<img width="1440" alt="Screen Shot 2020-02-09 at 4 19 00 PM" src="https://user-images.githubusercontent.com/58644761/74111587-d542ed00-4b63-11ea-90f8-e57cb30d697c.png">

**Comment by Curtly4** [comment]
can anyone offer any help?

**Comment by jbf-insidesherpa** [comment]
@Curtly4 sorry for getting back to this only now.

You're npm cannot find the python executable to use for one of its dependencies i.e node-gyp. You're also looking at the wrong slide where the solution to the problem you're facing is already discussed. The solution is in slide 25 of the guide:
https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v8.pdf

you need to tell npm where your python is installed e.g. something like:
npm config set python /path/to/executable/python

**Comment by Curtly4** [comment]
Thank you for your help.
