### ISSUE TITLE
npm install Errors

### ISSUE THREAD

**Issue by KevalPrajapati** [insidesherpa/JPMC-tech-task-2#262]
![Screenshot (54)](https://user-images.githubusercontent.com/63007835/87657587-a830e100-c778-11ea-8f07-be0828b7e14c.png)

**Comment by zuha-khalid-au3** [comment]
see if you have correct version of node and npm

**Comment by poorva-thosar** [comment]
First look for troubleshooting options given in first pdf of Task 2 i.e setup_devenv_m2_v8.pdf. (PDF slide 60 has troubleshooting options of windows).

If those troubleshooting don't work, then go to https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view and download files.
Then replace the node_modules inside your copy of the repo (cloned folder that you are using. Can be found at e.g C:\Users\YOUR-USER-NAME\JPMC-tech-task-2-PY3) with the one you
downloaded (make sure the folder is still named node_modules in your repo)
Afterwards, you can go ahead and just execute npm start (no need to run
npm install)

Make sure while running 'npm start', you at 'JPMC-tech-task-2-PY3' or 'JPMC-tech-task-2' 

Note :  Your working repo on command prompt must be 'JPMC-tech-task-2-PY3' or 'JPMC-tech-task-2' for npm install and npm start instructions.

**Comment by KevalPrajapati** [comment]
thanks.. But I solved the problem.

Thanks
