### ISSUE TITLE
Error when trying to "npm install"

### ISSUE THREAD

**Issue by jayvyer** [insidesherpa/JPMC-tech-task-2#27]
Hello!

I am trying to run the command "npm install" and there is an error when trying to build the projects.
I am running on a Windows 10, and initially had Case A error, but I downloaded Python 2.7 and added Python 27 to my path, as well as removing Python 3 from my path, and that "fixed" the error but now there is a different error message.

Here is a screenshot:

![error_message_JPM](https://user-images.githubusercontent.com/42682543/75831562-cece1c80-5d81-11ea-8f60-c1ab4e3e17c5.png)

Thank you

**Comment by jbf-insidesherpa** [comment]
@jayvyer sorry to get back to this only now.

Not sure if you've resolve the issue already.

If you've switched to python27 then based on your screenshot you're working with the wrong repo. Please use the JPMC-tech-task-2 not JPMC-tech-task-2-py3 repo

**Comment by riturajkush** [comment]
I am still facing same issue, switiching to repo for python 2.7 still gives the  same error.


![isuue](https://user-images.githubusercontent.com/33595729/80258788-b0114580-86a1-11ea-8ac3-69c87662dd87.png)
