### ISSUE TITLE
NPM Install warnings and error in start 

### ISSUE THREAD

**Issue by parthshuklaa-me** [insidesherpa/JPMC-tech-task-2#30]
![image](https://user-images.githubusercontent.com/57247572/77306046-10b50780-6d1d-11ea-9756-4cf8af13e5bc.png)

**Comment by htanwar922** [comment]
Run these:
    npm cache verify
    npm audit fix

**Comment by jbf-insidesherpa** [comment]
@htanwar922 and @parthshuklaa-me those warnings are fine. You shouldn't be blocked by any of those
