### ISSUE TITLE
issue with npm install 

### ISSUE THREAD

**Issue by samhithatarra** [insidesherpa/JPMC-tech-task-2#33]
<img width="684" alt="Screen Shot 2020-04-01 at 2 27 42 PM" src="https://user-images.githubusercontent.com/50003533/78188483-274a1580-7425-11ea-92f4-2057d5928d94.png">

**Comment by jbf-insidesherpa** [comment]
@samhithatarra those are just warnings and it means you're on the right track. You don't need to be blocked by those warnings.
