### ISSUE TITLE
npm install issue('npm' is not recognized as an internal or external command, operable program or batch file.)

### ISSUE THREAD

**Issue by Kapusana** [insidesherpa/JPMC-tech-task-2#34]
Hi,

I am having issues with installing npm on Windows OS. Nvm is successfully installed but whenever I try to execute an npm command I get a response that says " 'npm' is not recognized as an internal or external command,operable program or batch file. " ( as shown in the screenshot below).I tried to add the npm path(In the AppData folder)  to the system variables, make sure that I am executing the command in the JPMC directory and also download the node modules but I am still getting the same response.What would I be missing?

![npm issue install atempts](https://user-images.githubusercontent.com/51356125/78501020-7dec8200-778c-11ea-9b95-991899d6aa14.PNG)
![npm issue - system variable attempt](https://user-images.githubusercontent.com/51356125/78501021-7fb64580-778c-11ea-9612-8359af6c37ac.PNG)

**Comment by jay1499** [comment]
Try uninstalling 11.0.0v and reinstall it again, this should now install both nvm and npm- this worked for me with the same issue

**Comment by dheerajodha** [comment]
Hi @Kapusana as the solution suggested above,
If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by Kapusana** [comment]
Issue closed
