### ISSUE TITLE
Unable to find localhost:3000 and is showing error

### ISSUE THREAD

**Issue by kkpvit** [insidesherpa/JPMC-tech-task-2#41]
I am unable to find the window of localhost:after installing nvm
![Screen Shot 2020-04-22 at 2 01 44 PM](https://user-images.githubusercontent.com/58321253/80033582-d5376580-84a1-11ea-9bf0-3bba71ab52e2.png)

**Comment by nadahell** [comment]
Please, how did you solve this issue?
