### ISSUE TITLE
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

### ISSUE THREAD

**Issue by anishpai** [insidesherpa/JPMC-tech-task-2#42]
Hi, I am unable to resolve the following issue. Attaching screen shots of error while installing NPM.
![npm1](https://user-images.githubusercontent.com/47061835/80149428-46773580-85d4-11ea-827f-d5f7396d112f.JPG)
![npm2](https://user-images.githubusercontent.com/47061835/80149437-48d98f80-85d4-11ea-8936-70b978562154.JPG)

Could you please look into this and help me out? 
Thank you

**Comment by rohit270699** [comment]
DO you resolved it ??

**Comment by anishpai** [comment]
Hi. I managed to resolve the problem. It took me a couple of fixes.
using npm install/update do the following:
update bufferutil using cmd
install node gyp
install jpmorgan/perspective 

If it still doesnt work out, change the module @jpmorgan/perspective to @finos/perspective in the graph.tsx file
and then install finos/perspective.
Then you would need to-
update bufferutil using cmd
install node gyp
