### ISSUE TITLE
Error:I am unable to start npm

### ISSUE THREAD

**Issue by sumit076** [insidesherpa/JPMC-tech-task-2#43]
![Screenshot from 2020-04-24 03-37-25](https://user-images.githubusercontent.com/61472015/80154762-e4bbc900-85dd-11ea-9a0e-7ddec4dc5f4e.png)

But the server is started successully

![Screenshot from 2020-04-24 03-37-06](https://user-images.githubusercontent.com/61472015/80154789-f00ef480-85dd-11ea-8a0f-7cf43656dd1d.png)

**Comment by nikhilgy** [comment]
How did you solve this?? Even I got the same

**Comment by sumit076** [comment]
> How did you solve this?? Even I got the same

I forgot to change the directory to /JPMC-tech-task-2 in the first terminal that's why it was unable to start.. I hope this will help you...
