### ISSUE TITLE
Run Successful but nothing show anything on browser

### ISSUE THREAD

**Issue by bghanchi** [insidesherpa/JPMC-tech-task-2#45]
Hi, when I run the Reactjs app it's run successfully on console but nothing to show on browser.

![image](https://user-images.githubusercontent.com/30151850/80239626-31ef7780-867e-11ea-90dd-76121c90e69b.png)

![image](https://user-images.githubusercontent.com/30151850/80239641-3ae04900-867e-11ea-9b7c-7c7101500e48.png)

**Comment by Vishv07** [comment]
Run Server3.py parallelly

**Comment by dheerajodha** [comment]
Hi @bghanchi 
If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by bghanchi** [comment]
Hi, @dheerajodha Sure :)
