### ISSUE TITLE
HTTP Import Error in datafeed server.py file

### ISSUE THREAD

**Issue by ritzgupta29** [insidesherpa/JPMC-tech-task-2#50]
Traceback (most recent call last):
  File "C:\Users\heyit\JPMC-tech-task-2\datafeed\server.py", line 35, in <module>
    import http.server
ImportError: No module named http.server

**Comment by VaddadiSaiRahul** [comment]
@ritzgupta29  Do as the error says. You have import error , so install http library for your python version using pip (python 2) or pip3(python 3)

**Comment by ritzgupta29** [comment]
@VaddadiSaiRahul can you tell me the full command output because i couldnt get anywhere??
Please do reply

**Comment by ritzgupta29** [comment]
@VaddadiSaiRahul "Successfully installed docopt-0.6.2 httpserver-1.1.0 " still getting same error

**Comment by VaddadiSaiRahul** [comment]
try <b>pip install http</b> since you are using python 2

**Comment by ritzgupta29** [comment]
tried 
I am using both versions

**Comment by VaddadiSaiRahul** [comment]
Ok then try python3. datafeed3/server.py

**Comment by ritzgupta29** [comment]
tried this also....but nothing is working

**Comment by VaddadiSaiRahul** [comment]
what error is it giving for python3?

**Comment by ritzgupta29** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/51704222/80464901-12936b80-8958-11ea-9e72-0651ecc7815b.png)
now this is giving no error

**Comment by ritzgupta29** [comment]
but after running on python 3.8
it is giving the error
Traceback (most recent call last):
  File "C:\Users\heyit\JPMC-tech-task-2-PY3\datafeed\server3.py", line 320, in <module>
    run(App())
  File "C:\Users\heyit\JPMC-tech-task-2-PY3\datafeed\server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration

**Comment by VaddadiSaiRahul** [comment]
![image](https://user-images.githubusercontent.com/44061950/80467818-ff829a80-895b-11ea-8026-257ab8464d89.png)

Try the above once

**Comment by ritzgupta29** [comment]
tried but didn't working

**Comment by jshubhi** [comment]
> ![image](https://user-images.githubusercontent.com/44061950/80467818-ff829a80-895b-11ea-8026-257ab8464d89.png)
> 
> Try the above once

![Screenshot (97)](https://user-images.githubusercontent.com/63740932/80746821-1aadff80-8b40-11ea-9771-140715776db1.png)

No file named DataStreamer.ts in src.......I am facing the same issue as @ritzgupta29

**Comment by ritzgupta29** [comment]
> ![image](https://user-images.githubusercontent.com/44061950/80467818-ff829a80-895b-11ea-8026-257ab8464d89.png)
> 
> Try the above once

**Comment by ritzgupta29** [comment]
tried everything but something is missing and i dont know how to catch it.
