### ISSUE TITLE
Peer Dependencies "Webpack" Error

### ISSUE THREAD

**Issue by VaddadiSaiRahul** [insidesherpa/JPMC-tech-task-2#52]
I'm having problems during npm install. They require peer dependencies of WEBPACK, where one requires ONE VERSION of Webpack and other requires another version.PLease guide me through this.

![Screenshot from 2020-04-26 17-36-14](https://user-images.githubusercontent.com/44061950/80307356-27e88880-87e6-11ea-8a75-628d7dcd1530.png)

**Comment by natanAlper** [comment]
> I'm having problems during npm install. They require peer dependencies of WEBPACK, where one requires ONE VERSION of Webpack and other requires another version.PLease guide me through this.
> 
> ![Screenshot from 2020-04-26 17-36-14](https://user-images.githubusercontent.com/44061950/80307356-27e88880-87e6-11ea-8a75-628d7dcd1530.png)

How did you end up fixing this?

**Comment by VaddadiSaiRahul** [comment]
natanalper this is just a warning , you can ignore it. I got the same
error. Follow the steps given below :

1. Just run npm start
2. If it gives something like "react requires webpack version @4.x.x" or
something like that , then install webpack version for which error has
arised.
3. If you get no error , then proceed; At this point, you should have the
Perspecctive software running on your browser
