### ISSUE TITLE
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8085/query?id=1'.

### ISSUE THREAD

**Issue by AnneRajan** [insidesherpa/JPMC-tech-task-2#53]
![image](https://user-images.githubusercontent.com/50075447/80565428-0bc73000-8a0e-11ea-9982-76e27d7cd782.png)

**Comment by farhanzaman123** [comment]
Hey did anyone figure out how to resolve the issue?

**Comment by HariharaSubramanianM** [comment]
> ![image](https://user-images.githubusercontent.com/50075447/80565428-0bc73000-8a0e-11ea-9982-76e27d7cd782.png)

Hey, is there a solution for this issue?
