### ISSUE TITLE
NPM install Error 

### ISSUE THREAD

**Issue by shankyjoshi** [insidesherpa/JPMC-tech-task-2#56]
Can anybody help me i am not able to get what is this error during npm install
![image](https://user-images.githubusercontent.com/54698405/80721307-b11bfa00-8b1b-11ea-90ed-1de6e3eb5ba9.png)

**Comment by dheerajodha** [comment]
Hi @shank2512 , can you delete ~/.node-gyp folder and then the ~/.npmrc file, then restart your computer, and try again?
