### ISSUE TITLE
can't open file 'datafeed/server.py'.  'python3' version of the command still doesn't work

### ISSUE THREAD

**Issue by mara000** [insidesherpa/JPMC-tech-task-2#60]
can't open file 'datafeed/server.py': [Errno 2] No such file or directory
Tried the 'python3' version of the command and this shows up: 'python3' is not recognized as an internal or external command, operable program or batch file.
Could anyone please help me with this? Thank you!

![error_datafeed](https://user-images.githubusercontent.com/64498485/80834903-957f2500-8be9-11ea-989a-5e9db2caf678.JPG)

**Comment by karshil2309** [comment]
You could run simpy `python datafeed/server3.py` it works in my case, I have python 3.7.2 version!

**Comment by mara000** [comment]
> 
> 
> You could run simpy `python datafeed/server3.py` it works in my case, I have python 3.7.2 version!

Thank you for answering! Unfortunately, I have tried both versions and I get the errors that can be seen in the screenshot.
