### ISSUE TITLE
# Error: Can't find Python executable "

### ISSUE THREAD

**Issue by karshil2309** [insidesherpa/JPMC-tech-task-2#62]
![Screenshot (199)](https://user-images.githubusercontent.com/37497287/80855687-e3833f80-8c60-11ea-8a40-741b6b78b26f.png)

**Comment by karshil2309** [comment]
I have already set the python variable in Environment Variable, but still its not mapping with npm. What to do ?

**Comment by sumitav** [comment]
@karshil2309 Yes even am facing the same issue
Can someone please help us out for the same

**Comment by SHREYASH-MUKESH** [comment]
> @karshil2309 Yes even am facing the same issue
> Can someone please help us out for the same

hey just try uninsatlling everything and start from the very beginning 
_Originally posted by @SHREYASH-MUKESH in https://github.com/insidesherpa/JPMC-tech-task-2/issues/72#issuecomment-625046972_

this workked for me
if still you face any issue let me know

**Comment by josephhh-hub** [comment]
@SHREYASH-MUKESH  Can you explain how to uninstall everything and start from the beginning?

**Comment by SHREYASH-MUKESH** [comment]
delete the JP Morgan task files where you have downloaded it
then, delete the nvm from C drive
check for some files in users\....\appsdata\...
PS: dont uninstall PYTHON & VSCode
then after try to install from the beginning of the pdf following all steps

**Comment by josephhh-hub** [comment]
@SHREYASH-MUKESH Do you know where I can find something similar to a C drive on mac?

**Comment by karshil2309** [comment]
@SHREYASH-MUKESH The Error Still persists after removing everything and starting again from beginning. Nothing has changed. I dont know why npm cant map to python path?

**Comment by josephhh-hub** [comment]
@karshil2309 You can try downloading the node_modules file that the guide provides and replace the original node_modules file with the one you just downloaded. You can find it on slide 14 or 15.

**Comment by karshil2309** [comment]
@josephhh-hub Thanks it worked, but I didn't understood why my node modules were not working. I mean i tried to install from command line still its was a pain. Did u find any difference ?

**Comment by karshil2309** [comment]
Install Node Module as mentioned in Setup Pdf, it will solve the issue. For more knowledge u can open this issue again, as still having doubt how this thing works?
