### ISSUE TITLE
server.py is not loading / localhost is not loading

### ISSUE THREAD

**Issue by Abhishek-Hole** [insidesherpa/JPMC-tech-task-2#63]
help me with this
![1](https://user-images.githubusercontent.com/64624078/80873558-267ffa00-8cd7-11ea-8cfc-9261e2fa57a1.PNG)

**Comment by SHREYASH-MUKESH** [comment]
try using 
python datafeed/server3.py

**Comment by AshTiwari** [comment]
> try using
> python datafeed/server3.py

I had the same problem and this solution worked for me.

**Comment by BlAckbURn07** [comment]
> try using
> python datafeed/server3.py

on using this i am getting module not found error.
please help me

**Comment by dheerajodha** [comment]
Hi @Abhishek-Hole 
If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by dheerajodha** [comment]
Hi @BlAckbURn07 
Please whenever you are talking about errors, post sufficient information about error message either by copy pasting the error or by posting a screenshot would be better.

**Comment by Abhishek-Hole** [comment]
> Hi @BlAckbURn07 
> Please whenever you are talking about errors, post sufficient information about error message either by copy pasting the error or by posting a screenshot would be better.

Yes sir i have closed it as i am new in github so. i wasn't known about the closing issue i will take care from now onwards

**Comment by Abhishek-Hole** [comment]
> Hi @Abhishek-Hole 
> If you get some more errors, then post your error screenshots here.
> If you've already solved your issue, please close this issue, thanks!

Yes sir i have closed it as i am new in github so. i wasn't known about the closing issue i will take care from now onwards

**Comment by dheerajodha** [comment]
Don't call me sir :)
It's okay we all start somewhere! Thanks for closing the issue!
