### ISSUE TITLE
problem in downloading visual studio build tool

### ISSUE THREAD

**Issue by Vini2198** [insidesherpa/JPMC-tech-task-2#67]
Windows installed in my pc is 8.0 .And it is showing error regarding window version.
What should I do?
![IMG-20200505-WA0014](https://user-images.githubusercontent.com/47098056/81011062-ece4f580-8e74-11ea-86ca-345853ada0a8.jpg)

**Comment by dheerajodha** [comment]
Looks like the Visual Studio version that you're trying to install doesn't support Win 8.0
Instead of upgrading to WIndows 8.1, try to install Sublime Text or Brackets, they'll help you as well.

If you've already solved your issue, please close this issue, thanks!
