### ISSUE TITLE
Failed to run server3.py

### ISSUE THREAD

**Issue by suubh** [insidesherpa/JPMC-tech-task-2#69]
Even after changing the port number from 8080 to 8085 on both the files and all the firewall are off.It is showing the same error . npm start is working fine but just because of server3.py is not running it is not able to collect the data .
I am using Windows 10.
Please help asap.
The error is attached as below :
![Screenshot (170)](https://user-images.githubusercontent.com/47265493/81050208-38cb8500-8edd-11ea-9964-f5ad87f49e73.png)
Thank you.

**Comment by suubh** [comment]
It is working now

**Comment by RahulKalsangra** [comment]
> It is working now

How did it works???

**Comment by suubh** [comment]
@RahulKalsangra As you can see inside datafeed i was using Python server3.py.Instead of that dont go inside the datafeed directory and use this
datafeed/ python server3.py(Check this command from the PDF provided).
