### ISSUE TITLE
error occurred during the build time 

### ISSUE THREAD

**Issue by Aronray1** [insidesherpa/JPMC-tech-task-2#70]
Cannot find module '@jpmorganchase/perspective'.  TS2307

For a moment i could see the UI showing "Start Streaming data" button and after that i got this error.

**Comment by SHREYASH-MUKESH** [comment]
I'm also getting the same error
OS:

 WINDOW 10
Screenshot attached 
![Screenshot (16)](https://user-images.githubusercontent.com/60537522/81171258-b8c71d00-8fb9-11ea-8c9c-b220bda061f7.png)

**Comment by SHREYASH-MUKESH** [comment]
> Facing the same error on windows 10
i also have sam eissue but now its resolved
MY ISSUE RESOLVED 

just uninsatall every thing including the both git hub files which you have cloned/downloaded.
and restart the syatem .
again start from the very beginning
again try to install node/nvm
and it will surely work now
#72 
_Originally posted by @SHREYASH-MUKESH in https://github.com/insidesherpa/JPMC-tech-task-2/issues/72#issuecomment-625046972_

**Comment by dheerajodha** [comment]
Hi @Aronray1
If you get some more errors, then post your error screenshots or just comment here.
If you've already solved your issue, please close this issue, thanks!

**Comment by Aronray1** [comment]
This issue has been resolved. I am closing this issue.
