### ISSUE TITLE
Cannot find module '@jpmorganchase/perspective'. TS2307

### ISSUE THREAD

**Issue by SHREYASH-MUKESH** [insidesherpa/JPMC-tech-task-2#72]
Cannot find module '@jpmorganchase/perspective'. TS2307
Screenshot attached of the error i get in starting the server
OS- WINDOWS 10
![Screenshot (16)](https://user-images.githubusercontent.com/60537522/81171427-ff1c7c00-8fb9-11ea-8191-3b1f501d37d5.png)

**Comment by ikshitjalan** [comment]
Facing the same error on windows 10

**Comment by SHREYASH-MUKESH** [comment]
> Facing the same error on windows 10

MY ISSUE RESOLVED 
just uninsatall every thing including the both git hub files which you have cloned/downloaded.
and restart the syatem .
again start from the very beginning
again try to install node/nvm
and it will surely work now
