### ISSUE TITLE
Stop Iteration Error

### ISSUE THREAD

**Issue by sumit2498** [insidesherpa/JPMC-tech-task-2#76]
Hi I am having these  errors 
![Screenshot (146)](https://user-images.githubusercontent.com/20612008/81264654-63dde200-905f-11ea-8733-9245c511d0fc.png)
![Screenshot (147)](https://user-images.githubusercontent.com/20612008/81264660-69d3c300-905f-11ea-93a8-b5d6e4a36de7.png)

![Screenshot (145)](https://user-images.githubusercontent.com/20612008/81264467-15304800-905f-11ea-861f-b8042aba8e6b.png)

**Comment by JaideepVerma** [comment]
same here but not this much of

**Comment by dheerajodha** [comment]
Hi @sumit2498 , focusing on your 3rd image, you are running your command in wrong folder.
Please note :  you must be in **JPMC-tech-task-2-py3** directory and then execute :
**python** **datafeed/server.py**

**Comment by sumit2498** [comment]
Resolved
