### ISSUE TITLE
$npm install (problem occurred while i excuting this command).

### ISSUE THREAD

**Issue by Ashish-peter** [insidesherpa/JPMC-tech-task-2#78]
![Screenshot (47)](https://user-images.githubusercontent.com/59234131/81278549-76621680-9073-11ea-936a-58961d2ea150.png)

**Comment by Amol2807** [comment]
Run the following command instead 
npm install --force
It should work

**Comment by Ashish-peter** [comment]
> 
> 
> Run the following command instead
> npm install --force
> After that type
> npm start

it's work

**Comment by Ashish-peter** [comment]
> 
> 
> Run the following command instead
> npm install --force
> After that type
> npm start

it's work 
![image](https://user-images.githubusercontent.com/59234131/81289485-20e23580-9084-11ea-88ad-75930d143116.png)
