### ISSUE TITLE
Cannot find module '@jpmorganchase/perspective

### ISSUE THREAD

**Issue by prakhar213** [insidesherpa/JPMC-tech-task-2#80]
npm install and npm start both are not successfully executing. I have seriously tried damn hard on this issue but nothing worked out. Below image will demonstrate the output I am getting after running npm start command.
![post](https://user-images.githubusercontent.com/64911804/81329406-265b7200-90bc-11ea-98ce-a693e4464b71.PNG)

**Comment by venera-k** [comment]
https://github.com/insidesherpa/JPMC-tech-task-2/issues/47#issuecomment-624514076 This solution worked for me

**Comment by prakhar213** [comment]
@venera-k  nvm v11.0.0 is successfully installed but when I run nvm use 11.0.0 it shows --->
 exit status 1: 'C:\Users\Prakhar' is not recognized as an internal or external command,
operable program or batch file.

**Comment by LordUttam** [comment]
Try running npm install again in the datafeed folder. You might get an error like this a few lines below:
gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
Just run npm install --ignore-scripts . Ignore the warnings. And go for npm start again.
It should run properly now. NO need to replace the node_modules folder. 
*Also remember to post issues in the proper repositories. This repo is for py2 where as you are using py3.

**Comment by prakhar213** [comment]
datafeed folder means running the npm install after running python3 datafeed/server3.py command ?

**Comment by prakhar213** [comment]
This output came up
![post](https://user-images.githubusercontent.com/64911804/81428809-6f71fb80-917a-11ea-9f86-c60bf58efc0c.PNG)

**Comment by prakhar213** [comment]
Thank you so very much ...It worked.. Was stuck in this problem from 2 days finally feeling happy
