### ISSUE TITLE
Could not find index.html

### ISSUE THREAD

**Issue by sudhanshu-mallick** [insidesherpa/JPMC-tech-task-2#83]
I have downloaded node_modules folder as I had some issues with : npm install. I then moved it to the required directory. After that, in order to start server from client side, when I used: npm start command, it shows something like below:
`C:\Users\SUDHANSHU MALLICK>npm start

> bank-merge-co-task-2@0.1.0 start C:\Users\SUDHANSHU MALLICK
> react-scripts start

Could not find a required file.
  Name: index.html
  Searched in: C:\Users\SUDHANSHU MALLICK\public
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SUDHANSHU MALLICK\AppData\Roaming\npm-cache\_logs\2020-05-08T17_30_13_863Z-debug.log`

Please help me get this error resolved. 
![Capture](https://user-images.githubusercontent.com/44547947/81432652-ee6a3280-9180-11ea-8735-d9b16c405714.PNG)

**Comment by dheerajodha** [comment]
Hi @sudhanshu-mallick seems like maybe the node_modules package have some missing files.
Can you try again by deleting node_modules folder and run :
1) npm install
2) npm start

As mentioned by you, you have tried this earlier so can you mention what errors you got?
If you've already solved your issue, please close this issue, thanks!
