### ISSUE TITLE
server application stuck. CMD doesn't respond after this.

### ISSUE THREAD

**Issue by IFHAM99** [insidesherpa/JPMC-tech-task-2#85]
![Capture](https://user-images.githubusercontent.com/50768671/81460586-eb446600-91c3-11ea-8edf-f5e64036ca7e.PNG)

**Comment by dheerajodha** [comment]
@IFHAM99 Please close this issue since it's a duplicate issue, thanks!

**Comment by IFHAM99** [comment]
The issue is resolved, thanks.
