### ISSUE TITLE
ERROR in npm install

### ISSUE THREAD

**Issue by ishita527** [insidesherpa/JPMC-tech-task-2#87]
I'am not able to understand why this command isnt running? I am not facing the npm config to python error since I've only 1 version of Python. Also i have got the server up and running so no issues with Python environment variable as well. Is it possible the problem is with the command **npm config set msvs_version 2017** since I have installed the 2019 built tools version? 
But I also tried running the command **npm config set msvs_version 2019** and then also npm install is showing error. Please help.

**Comment by Achaleshwar-singh** [comment]
You don't need to install c++ build tools as we have simple solution for this problem visit page no 65 in given pdf from there you can download node_modules. Just replace that node_modules with the actual node_modules which are in your JPMC-tech-task-2 folder. After doing this you can simple start npm, no need to install npm and other dependencies.
try this if you still have any issue please let me know.

**Comment by dheerajodha** [comment]
Hi @ishita527 as the solution is mentioned above, 
If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!
