### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Swapnadeep2K** [insidesherpa/JPMC-tech-task-2#89]
![Screenshot (245)](https://user-images.githubusercontent.com/65028648/81472870-38eabe00-9218-11ea-8903-dece478b838c.png)
how to rectify this?

**Comment by dheerajodha** [comment]
Hi @Swapnadeep2K 
Have a look here : 
https://github.com/insidesherpa/JPMC-tech-task-2/issues/138
https://github.com/insidesherpa/JPMC-tech-task-2/issues/47

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!
