### ISSUE TITLE
NetworkError: Failed to execute 'send' on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by manthanjaiswal2** [insidesherpa/JPMC-tech-task-2#9]
Hello, There is an issue while clicking the "Start Streaming Data". It gives NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'. Please resolve this as soon as possible.
![Screenshot (28)](https://user-images.githubusercontent.com/35054059/68100626-fb1a7f00-feee-11e9-9363-b4fc3a453e93.png)

**Comment by jbf-insidesherpa** [comment]
@manthanjaiswal2 can I confirm if you're also running the datafeed/server.py alongside the client application (i.e. what you see on the browser?)

For the client / browser application to work fully, you need to be also running the server application that takes care of listening to the clients requests. The server application is the python script in datafeed folder i.e. datafeed/server.py. You're supposed to run it like `python datafeed/server.py` (assuming your terminal's current working directory is in the repository).

The error you're getting is indicative that you're not running the server script.

Let me know if this resolves your issue.

**Comment by manthanjaiswal2** [comment]
> @manthanjaiswal2 can I confirm if you're also running the datafeed/server.py alongside the client application (i.e. what you see on the browser?)
> 
> For the client / browser application to work fully, you need to be also running the server application that takes care of listening to the clients requests. The server application is the python script in datafeed folder i.e. datafeed/server.py. You're supposed to run it like `python datafeed/server.py` (assuming your terminal's current working directory is in the repository).
> 
> The error you're getting is indicative that you're not running the server script.
> 
> Let me know if this resolves your issue.

It is working. Thanks for the help sir..

**Comment by jbf-insidesherpa** [comment]
@manthanjaiswal2 no worries.

**Comment by sushilca98** [comment]
![Error_JPMC](https://user-images.githubusercontent.com/53387282/70369467-867c8c80-186e-11ea-92e4-f07c9f2b2544.PNG)
![Server run](https://user-images.githubusercontent.com/53387282/70369495-1de1df80-186f-11ea-8533-c8a8f59efd41.PNG)

I tried everything but still it gives me same result as 
"NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'  "
Please help me asap and please let me know what I am doing wrong.
Please also explain me the proper way to run the server script.
