### ISSUE TITLE
Not able to use "npm start". stuck at this step

### ISSUE THREAD

**Issue by jigneshk3108** [insidesherpa/JPMC-tech-task-2#96]
![image](https://user-images.githubusercontent.com/36676719/81504009-9a885680-9304-11ea-8300-5d550a48d67b.png)
![image](https://user-images.githubusercontent.com/36676719/81504042-d3283000-9304-11ea-887b-a6d5e698e3a8.png)

**Comment by JanardhanSingh98** [comment]
use `npm install --ignore-scripts`

**Comment by jigneshk3108** [comment]
Thanks bro, this worked for me
